Improve output visual and syntax

diff --git a/file-backup b/file-backup
--- a/file-backup
+++ b/file-backup
@@ -10,39 +10,40 @@ readonly C_CURRENT_BACKUP="backed_up_files"
 readonly C_TMP_BACKUP="backed_up_files_tmp"
 
 # shellcheck disable=SC2206
-#   The array is purposefully unquoted to allow for word splitting, for easy array
-#   iteration.
+#   The array is purposefully unquoted to allow for for easy array iteration.
 readonly C_FILES_TO_BACK_UP=($E_FILES_TO_BACK_UP)
 
 
 ####[ Main ]############################################################################
 
 
-echo "We will now back up the following files:${E_CYAN}"
+echo "{$E_INFO}We will now back up the following files:${E_CYAN}"
 for file in "${C_FILES_TO_BACK_UP[@]}";
-    do echo "    $file"
+    do echo "${E_INFO}    $file"
 done
 echo -n "$E_NC"
-read -rp "Press [Enter] to continue."
+read -rp "${E_NOTICE}Press [Enter] to continue."
 
 [[ ! -d $C_TMP_BACKUP ]] && mkdir "$C_TMP_BACKUP"
 
-echo "Backing up important files into '$C_TMP_BACKUP'..."
+echo "${E_INFO}Backing up important files into '$C_TMP_BACKUP'..."
 for file in "${C_FILES_TO_BACK_UP[@]}"; do
     if [[ -f $file ]]; then
-        cp -f "$file" "$C_TMP_BACKUP" \
-            || echo "${E_RED}Failed to back up ${file}${E_NC}" >&2
+        cp -f "$file" "$C_TMP_BACKUP" || {
+            echo "${E_ERROR}Failed to back up '${file}'" >&2
+            exit 1
+        }
     else
-        echo "${E_YELLOW}${file} could not be found${E_NC}"
+        echo "${E_WARNING}'${file}' could not be found${E_NC}"
     fi
 done
 
 if [[ -d $C_CURRENT_BACKUP ]]; then
-    echo "Renaming the old backups and moving them to '$C_TMP_BACKUP'..."
+    echo "${E_INFO}Renaming and moving old backups to '$C_TMP_BACKUP'..."
     while read -r file; do
         if [[ ! $file =~ ^.*.old$ ]]; then
             cp "$C_CURRENT_BACKUP"/"$file" "$C_TMP_BACKUP"/"$file".old || {
-                echo "${E_RED}Failed to rename and move ${file}${E_NC}" >&2
+                echo "${E_ERROR}Failed to rename and move '${file}'${E_NC}" >&2
                 exit 1
             }
         fi
@@ -51,12 +52,13 @@ fi
 
 
 if [[ -d $C_CURRENT_BACKUP ]]; then
-    echo "Removing '$C_CURRENT_BACKUP' and renaming '$C_TMP_BACKUP' as '$C_CURRENT_BACKUP'..."
+    echo "${E_INFO}Removing '$C_CURRENT_BACKUP' and renaming '$C_TMP_BACKUP' as" \
+        "'$C_CURRENT_BACKUP'..."
     rm -rf "$C_CURRENT_BACKUP" && mv "$C_TMP_BACKUP" "$C_CURRENT_BACKUP"
 else
-    echo "Renaming '$C_TMP_BACKUP' as '$C_CURRENT_BACKUP'..."
+    echo "${E_INFO}Renaming '$C_TMP_BACKUP' as '$C_CURRENT_BACKUP'..."
     mv "$C_TMP_BACKUP" "$C_CURRENT_BACKUP"
 fi
 
 echo ""
-read -rp "Press [Enter] to return to the main menu"
+read -rp "${E_NOTICE}Press [Enter] to return to the main menu"
diff --git a/installer-prep b/installer-prep
--- a/installer-prep
+++ b/installer-prep
@@ -20,7 +20,15 @@ E_RED="$(printf '\033[1;31m')"
 E_NC="$(printf '\033[0m')"
 E_GREY="$(printf '\033[0;90m')"
 E_CLRLN="$(printf '\r\033[K')"
-export E_YELLOW E_GREEN E_CYAN E_RED E_NC E_GREY E_CLRLN
+export E_YELLOW E_GREEN E_CYAN E_ERROR E_NC E_GREY E_CLRLN
+
+## Short-hand colorized messages.
+E_SUCCESS="${E_GREEN}==>${E_NC} "
+E_WARNING="${E_YELLOW}==>${E_NC} "
+E_ERROR="${E_RED}ERROR:${E_NC} "
+E_INFO="${E_BLUE}==>${E_NC} "
+E_NOTE="${E_CYAN}==>${E_NC} "
+export E_SUCCESS E_WARNING E_ERROR E_INFO E_NOTE
 
 
 ####[ Functions ]#######################################################################
@@ -52,8 +60,8 @@ detect_sys_info() {
 # Download the latest version of 'linuxAIO' if $E_LINUXAIO_REVISION and
 # $C_CURRENT_LINUXAIO_REVISION aren't of equal value.
 linuxAIO_update() {
-    echo -n "${E_YELLOW}You are using an older version of 'linuxAIO'. "
-    read -rp "Press [Enter] to download the latest version.${E_NC}"
+    echo "${E_WARNING}You are using an older version of 'linuxAIO'"
+    read -rp "${E_NOTICE}Press [Enter] to download the latest version"
     echo "Downloading latest version of 'linuxAIO'..."
 
     ## Due to changes in 'linuxAIO', the existing configurations cannot be directly
@@ -66,16 +74,16 @@ linuxAIO_update() {
     #   that the if statement doesn't need to test for $E_LINUXAIO_REVISION.
     if ((_LINUXAIO_REVISION <= 38)); then
         if [[ -f linuxAIO.sh ]]; then
-            echo "Backing up 'linuxAIO.sh' as 'linuxAIO.sh.old'..."
+            echo "${E_INFO}Backing up 'linuxAIO.sh' as 'linuxAIO.sh.old'..."
             mv linuxAIO.sh linuxAIO.sh.old
         elif [[ -f linuxAIO ]]; then
-            echo "Backing up 'linuxAIO' as 'linuxAIO.old'..."
+            echo "${E_INFO}Backing up 'linuxAIO' as 'linuxAIO.old'..."
             mv linuxAIO linuxAIO.old
         fi
 
         curl -O "$_RAW_URL"/linuxAIO && sudo chmod +x linuxAIO
-        echo "${E_CYAN}NOT applying existing configurations to 'linuxAIO'"
-        echo "${E_GREEN}Successfully downloaded the newest version of 'linuxAIO'.${E_NC}"
+        echo "${E_NOTICE}NOT applying existing configurations to 'linuxAIO'"
+        echo "${E_SUCCESS}Successfully downloaded the newest version of 'linuxAIO'.${E_NC}"
     ## Download the newest version of 'linuxAIO' and apply existing changes to it.
     else
         local installer_branch
@@ -88,8 +96,7 @@ linuxAIO_update() {
         bot_install_version_found="$?"
 
         curl -O "$E_RAW_URL"/linuxAIO && sudo chmod +x linuxAIO
-
-        echo "Applying existing configurations to the new 'linuxAIO'..."
+        echo "${E_INFO}Applying existing configurations to the new 'linuxAIO'..."
 
         [[ $installer_branch_found == 0 ]] \
             && sed -i "s/^installer_branch=.*/$installer_branch/" linuxAIO
@@ -97,8 +104,8 @@ linuxAIO_update() {
         [[ $bot_install_version_found == 0 ]] \
             && sed -i "s/^export E_BOT_INSTALL_VERSION=.*/$bot_install_version/" linuxAIO
 
-        echo "${E_GREEN}Successfully downloaded the newest version of 'linuxAIO' and" \
-            "applied existing changes${E_NC}"
+        echo "${E_SUCCESS}Successfully downloaded the newest version of 'linuxAIO' and" \
+            "applied existing changes"
     fi
 
     clean_up "0" "Exiting" "true"
@@ -108,12 +115,12 @@ linuxAIO_update() {
 # Provide the end-user with the option to continue, even if their system isn't
 # officially supported.
 unsupported() {
-    echo "${E_RED}Your operating system is not OFFICIALLY supported for the" \
+    echo "${E_ERROR}Your operating system is not OFFICIALLY supported for the" \
         "installation, setup, and/or use of NadekoBot" >&2
-    echo "${E_YELLOW}WARNING: By continuing, you accept that unexpected behaviors" \
-        "may occur. If you run into any errors or problems with the installation and" \
-        "use of the NadekoBot, you are on your own.${E_NC}"
-    read -rp "Would you like to continue anyways? [y/N] " choice
+    echo "${E_WARNING}${E_YELLOW}WARNING${E_NC}: By continuing, you accept that" \
+        "unexpected behaviors may occur. If you run into any errors or problems with" \
+        "the installation and use of the NadekoBot, you are on your own."
+    read -rp "${E_INFO}Would you like to continue anyways? [y/N] " choice
 
     choice=${choice,,}
     case "$choice" in
@@ -148,9 +155,9 @@ clean_up() {
         "nadeko-latest-installer" "nadeko-runner" "nadeko-main-installer")
 
     if [[ $clean_up_text == true ]]; then
-        echo -e "\n\nCleaning up..."
+        echo -e "\n\n${E_INFO}Cleaning up..."
     else
-        echo -e "\nCleaning up..."
+        echo -e "\n${E_INFO}Cleaning up..."
     fi
 
     cd "$E_WORKING_DIR" || E_STDERR "Failed to move to NadekoBot's root directory" "1"
@@ -160,7 +167,7 @@ clean_up() {
         [[ -f $file ]] && rm "$file"
     done
 
-    echo "$output_text..."
+    echo "${E_INFO}$output_text..."
     exit "$exit_code"
 }
 
@@ -188,7 +195,7 @@ E_DOWNLOAD_SCRIPT() {
     local script_name="$1"
     local script_output="${2:-false}"
 
-    [[ $script_output == true ]] && printf "Downloading '%s'..." "$script_name"
+    [[ $script_output == true ]] && printf "${E_INFO}Downloading '%s'..." "$script_name"
 
     curl -O -s "$E_RAW_URL"/"$script_name"
     sudo chmod +x "$script_name"
@@ -209,7 +216,7 @@ E_STDERR() {
     local exit_code="${2:-}"
     local additional_message="${3:-}"
 
-    echo "${E_RED}$error_message${E_NC}" >&2
+    echo "${E_ERROR}$error_message" >&2
     [[ $additional_message ]] && echo -e "$additional_message" >&2
     [[ $exit_code ]] && exit "$exit_code"
 }
@@ -234,8 +241,8 @@ fi
 
 # Change the working directory to the location of the executed script.
 cd "${0%/*}" || {
-    echo "${E_RED}Failed to change working directory" >&2
-    echo "${E_CYAN}Change your working directory to that of the executed script${E_NC}"
+    echo "${E_ERROR}Failed to change working directory" >&2
+    echo "${E_NOTICE}Change your working directory to that of the executed script"
     clean_up "1" "Exiting"
 }
 
@@ -261,18 +268,18 @@ Distro Version: $E_VER
 "
 
 ### Check if the operating system is supported by NadekoBot and the installer.
-if [[ $bits = 64 ]]; then
-    if [[ $E_DISTRO = "ubuntu" ]]; then
+if [[ $bits == 64 ]]; then
+    if [[ $E_DISTRO == "ubuntu" ]]; then
         case "$E_VER" in
             22.04|20.04|18.04) execute_main_installer ;;
             *)                 unsupported ;;
         esac
-    elif [[ $E_DISTRO = "debian" ]]; then
+    elif [[ $E_DISTRO == "debian" ]]; then
         case "$E_SVER" in
             11|10) execute_main_installer ;;
             *)     unsupported ;;
         esac
-    elif [[ $E_DISTRO = "linuxmint" ]]; then
+    elif [[ $E_DISTRO == "linuxmint" ]]; then
         case "$E_SVER" in
             21|20) execute_main_installer ;;
             *)     unsupported ;;
diff --git a/nadeko-main-installer b/nadeko-main-installer
--- a/nadeko-main-installer
+++ b/nadeko-main-installer
@@ -99,7 +99,7 @@ E_STOP_SERVICE() {
     if [[ $E_SERVICE_STATUS == "active" ]]; then
         echo "Stopping '$E_SERVICE_NAME'..."
         sudo systemctl stop "$E_SERVICE_NAME" || {
-            echo "${E_RED}Failed to stop '$E_SERVICE_NAME'" >&2
+            echo "${E_ERROR}Failed to stop '$E_SERVICE_NAME'" >&2
             echo "${E_CYAN}You will need to restart '$E_SERVICE_NAME' to apply any" \
                 "updates to NadekoBot${E_NC}"
             return 1
@@ -232,10 +232,10 @@ while true; do
     ## Options 2 and 3 remain enabled, if 'NadekoRun' exists.
     elif [[ -f NadekoRun ]]; then
         ## Option 5 remains enabled, if NadekoBot's service is running.
-        if [[ $E_SERVICE_STATUS = "active" ]]; then
+        if [[ $E_SERVICE_STATUS == "active" ]]; then
             run_mode_status=" ${E_GREEN}(Running in this mode)${E_NC}"
         ## Disable option 5 if NadekoBot's service NOT running.
-        elif [[ $E_SERVICE_STATUS = "inactive" ]]; then
+        elif [[ $E_SERVICE_STATUS == "inactive" ]]; then
             opt_five_dis=true
             opt_five_text="${E_GREY}${opt_five_text}${dis_opt_v2}${E_NC}"
             run_mode_status=" ${E_YELLOW}(Set up to run in this mode)${E_NC}"
@@ -273,7 +273,7 @@ while true; do
             ## B.1.
             if "$opt_one_dis"; then
                 clear -x
-                echo "${E_RED}Option 1 is currently disabled${E_NC}"
+                echo "${E_ERROR}Option 1 is currently disabled${E_NC}"
                 disabled_reasons
                 continue
             fi
@@ -299,7 +299,7 @@ while true; do
             ## B.1.
             if "$opt_two_and_three_dis"; then
                 clear -x
-                echo "${E_RED}Option $choice is currently disabled${E_NC}"
+                echo "${E_ERROR}Option $choice is currently disabled${E_NC}"
                 disabled_reasons
                 continue
             fi
@@ -314,7 +314,7 @@ while true; do
             clear -x
 
             # If option 2 was executed...
-            if [[ $choice = 2 ]]; then
+            if [[ $choice == 2 ]]; then
                 export E_CODENAME="NadekoRun"
                 printf "We will now run NadekoBot in the background. "
             # If option 3 was executed...
@@ -338,7 +338,7 @@ while true; do
             clear -x
             ## B.1.
             if "$opt_five_dis"; then
-                echo "${E_RED}Option 5 is currently disabled${E_NC}"
+                echo "${E_ERROR}Option 5 is currently disabled${E_NC}"
                 echo ""
                 continue
             fi
@@ -356,7 +356,7 @@ while true; do
             ## B.1.
             if "$opt_seven_dis"; then
                 clear -x
-                echo "${E_RED}Option 7 is currently disabled${E_NC}"
+                echo "${E_ERROR}Option 7 is currently disabled${E_NC}"
                 disabled_reasons
                 continue
             fi
@@ -371,7 +371,7 @@ while true; do
             ;;
         *)
             clear -x
-            echo "${E_RED}Invalid input: '$choice' is not a valid option${E_NC}" >&2
+            echo "${E_ERROR}Invalid input: '$choice' is not a valid option${E_NC}" >&2
             echo ""
             ;;
     esac
diff --git a/nadeko-runner b/nadeko-runner
--- a/nadeko-runner
+++ b/nadeko-runner
@@ -11,7 +11,7 @@
 
 
 ### Indicate which actions to be performed on NadekoBot's service.
-if [[ $E_CODENAME = "NadekoRun" ]]; then
+if [[ $E_CODENAME == "NadekoRun" ]]; then
     readonly C_LOWER="disable"    # A.1.
     readonly C_UPPER="Disabling"  # B.1.
 else
@@ -25,7 +25,7 @@ systemd_version=$(systemd --version | awk 'NR==1 {print $2}')
 ## NOTE:
 ##  'StandardOutput' and 'StandardError' no longer supports 'syslog' starting in
 ##  version 246 of systemd.
-if (( systemd_version >= 246)); then
+if ((systemd_version >= 246)); then
     readonly C_SERVICE_CONTENT="[Unit]
 Description=NadekoBot service
 After=network.target
@@ -74,8 +74,10 @@ unset systemd_version
 
 
 # Check if the service exists.
-if [[ -f $E_SERVICE ]]; then echo "Updating '$E_SERVICE_NAME'..."
-else                        echo "Creating '$E_SERVICE_NAME'..."
+if [[ -f $E_SERVICE ]]; then
+    echo "Updating '$E_SERVICE_NAME'..."
+else
+    echo "Creating '$E_SERVICE_NAME'..."
 fi
 
 {
@@ -83,7 +85,7 @@ fi
     echo "$C_SERVICE_CONTENT" | sudo tee "$E_SERVICE" &>/dev/null \
         && sudo systemctl daemon-reload
 } || {
-    echo "${E_RED}Failed to create '$E_SERVICE_NAME'" >&2
+    echo "${E_ERROR}Failed to create '$E_SERVICE_NAME'" >&2
     echo "${E_CYAN}This service must exist for NadekoBot to work${E_NC}"
     read -rp "Press [Enter] to return to the installer menu"
     exit 3
@@ -92,16 +94,14 @@ fi
 ## Disable/enable the service.
 echo "$C_UPPER '$E_SERVICE_NAME'..."
 sudo systemctl "$C_LOWER" "$E_SERVICE_NAME" || {
-    echo "${E_RED}Failed to $C_LOWER '$E_SERVICE_NAME'" >&2
+    echo "${E_ERROR}Failed to $C_LOWER '$E_SERVICE_NAME'" >&2
     echo "${E_CYAN}This service must be ${C_LOWER}d in order to use this run mode${E_NC}"
     read -rp "Press [Enter] to return to the installer menu"
     exit 3
 }
 
-# Check if 'NadekoRun' exists.
 if [[ -f NadekoRun ]]; then
     echo "Updating 'NadekoRun'..."
-## Create 'NadekoRun' if it doesn't exist.
 else
     echo "Creating 'NadekoRun'..."
     touch NadekoRun
@@ -109,7 +109,7 @@ else
 fi
 
 ## Add the code required to run NadekoBot in the background, to 'NadekoRun'.
-if [[ $E_CODENAME = "NadekoRun" ]]; then
+if [[ $E_CODENAME == "NadekoRun" ]]; then
     printf '%s\n' \
         "#!/bin/bash" \
         "" \
@@ -169,10 +169,10 @@ else
 fi
 
 ## Restart the service if it is currently running.
-if [[ $E_SERVICE_STATUS = "active" ]]; then
+if [[ $E_SERVICE_STATUS == "active" ]]; then
     echo "Restarting '$E_SERVICE_NAME'..."
     sudo systemctl restart "$E_SERVICE_NAME" || {
-        echo "${E_RED}Failed to restart '$E_SERVICE_NAME'${E_NC}" >&2
+        echo "${E_ERROR}Failed to restart '$E_SERVICE_NAME'${E_NC}" >&2
         read -rp "Press [Enter] to return to the installer menu"
         exit 3
     }
@@ -180,7 +180,7 @@ if [[ $E_SERVICE_STATUS = "active" ]]; then
 else
     echo "Starting '$E_SERVICE_NAME'..."
     sudo systemctl start "$E_SERVICE_NAME" || {
-        echo "${E_RED}Failed to start '$E_SERVICE_NAME'${E_NC}" >&2
+        echo "${E_ERROR}Failed to start '$E_SERVICE_NAME'${E_NC}" >&2
         read -rp "Press [Enter] to return to the installer menu"
         exit 3
     }
