Update style of exported variables

diff --git a/file-backup b/file-backup
--- a/file-backup
+++ b/file-backup
@@ -1,7 +1,7 @@
 #!/bin/bash
 #
 # Back up some of the more important files, that of which, can be configured by adding
-# to $_FILES_TO_BACK_UP in 'linuxAIO'.
+# to $E_FILES_TO_BACK_UP in 'linuxAIO'.
 #
 ########################################################################################
 #### [ Variables ]
@@ -14,7 +14,7 @@ tmp_backup="important_file_backup_tmp"
 # REASON: The array is purposefully unquoted to allow for word splitting, for easy
 #         arrray itteration.
 # shellcheck disable=SC2206
-files_to_back_up=($_FILES_TO_BACK_UP)
+files_to_back_up=($E_FILES_TO_BACK_UP)
 
 
 #### End of [ Variables ]
@@ -22,10 +22,10 @@ files_to_back_up=($_FILES_TO_BACK_UP)
 #### [ Main ]
 
 
-echo "We will now back up the following files:${_CYAN}"
+echo "We will now back up the following files:${E_CYAN}"
 for file in "${files_to_back_up[@]}"; do echo "    $file"
 done
-echo -n "$_NC"
+echo -n "$E_NC"
 read -rp "Press [Enter] to continue."
 
 ## Create '$tmp_backup' if it doesn't exist.
@@ -36,9 +36,9 @@ echo "Backing up important files into '$tmp_backup'..."
 for file in "${files_to_back_up[@]}"; do
     if [[ -f $file ]]; then
         cp -f "$file" "$tmp_backup" \
-            || echo "${_RED}Failed to back up ${file}${_NC}" >&2
+            || echo "${E_RED}Failed to back up ${file}${E_NC}" >&2
     else
-        echo "${_YELLOW}${file} could not be found${_NC}"
+        echo "${E_YELLOW}${file} could not be found${E_NC}"
     fi
 done
 
@@ -49,7 +49,7 @@ if [[ -d $current_backup ]]; then
     while read -r file; do
         if [[ ! $file =~ ^.*.old$ ]]; then
             cp "$current_backup"/"$file" "$tmp_backup"/"$file".old || {
-                echo "${_RED}Failed to rename and move ${file}${_NC}" >&2
+                echo "${E_RED}Failed to rename and move ${file}${E_NC}" >&2
                 exit 1
             }
         fi
diff --git a/installer-prep b/installer-prep
--- a/installer-prep
+++ b/installer-prep
@@ -17,18 +17,19 @@ main_installer="nadeko-main-installer"
 # number. Instead of only being used to represent the relationship between this script
 # and 'linuxAIO', it represents major changes to the installer that requires a change in
 # behavior, that would otherwise result in conflict with older verisons of the script.
+# TODO: Remove variable; it's not being used.
 export _REVISION_NUMBER=1
 
 ## Modify output text color.
 # shellcheck disable=SC2155
 {
-    export _YELLOW="$(printf '\033[1;33m')"
-    export _GREEN="$(printf '\033[0;32m')"
-    export _CYAN="$(printf '\033[0;36m')"
-    export _RED="$(printf '\033[1;31m')"
-    export _NC="$(printf '\033[0m')"
-    export _GREY="$(printf '\033[0;90m')"
-    export _CLRLN="$(printf '\r\033[K')"
+    export E_YELLOW="$(printf '\033[1;33m')"
+    export E_GREEN="$(printf '\033[0;32m')"
+    export E_CYAN="$(printf '\033[0;36m')"
+    export E_RED="$(printf '\033[1;31m')"
+    export E_NC="$(printf '\033[0m')"
+    export E_GREY="$(printf '\033[0;90m')"
+    export E_CLRLN="$(printf '\r\033[K')"
 }
 
 
@@ -47,40 +48,40 @@ detect_sys_info() {
     if [[ -f /etc/os-release ]]; then
         # shellcheck disable=SC1091
         . /etc/os-release
-        _DISTRO="$ID"
-        _VER="$VERSION_ID"  # Version: x.x.x...
-        _SVER=${_VER//.*/}  # Version: x
+        E_DISTRO="$ID"
+        E_VER="$VERSION_ID"  # Version: x.x.x...
+        E_SVER=${E_VER//.*/}  # Version: x
         pname="$PRETTY_NAME"
     else
-        _DISTRO=$(uname -s)
-        _VER=$(uname -r)
+        E_DISTRO=$(uname -s)
+        E_VER=$(uname -r)
     fi
 
     ## Identify bit and architecture type.
     case $(uname -m) in
-        x86_64) bits="64"; _ARCH="x64" ;;
-        i*86)   bits="32"; _ARCH="x86" ;;
-        armv*)  bits="32"; _ARCH="?" ;;
-        *)      bits="?";  _ARCH="?" ;;
+        x86_64) bits="64"; E_ARCH="x64" ;;
+        i*86)   bits="32"; E_ARCH="x86" ;;
+        armv*)  bits="32"; E_ARCH="?" ;;
+        *)      bits="?";  E_ARCH="?" ;;
     esac
 }
 
 ########
-# Download the latest version of 'linuxAIO' if $_LINUXAIO_REVISION and
+# Download the latest version of 'linuxAIO' if $E_LINUXAIO_REVISION and
 # $current_linuxAIO_revision aren't of equal value.
 #
 # Arguments:
 #  None
 ########
 linuxAIO_update() {
-    echo -n "${_YELLOW}You are using an older version of 'linuxAIO'. "
-    read -rp "Press [Enter] to download the latest version.${_NC}"
+    echo -n "${E_YELLOW}You are using an older version of 'linuxAIO'. "
+    read -rp "Press [Enter] to download the latest version.${E_NC}"
     echo "Downloading latest version of 'linuxAIO'..."
 
     ## Only download the newest version of 'linuxAIO', as there are some incompatible
     ## changes to 'linuxAIO' making it difficult or impossible to merge existing
     ## configurations.
-    if ((_LINUXAIO_REVISION <= 37)); then
+    if ((E_LINUXAIO_REVISION <= 37)); then
         if [[ -f linuxAIO.sh ]]; then
             echo "Backing up 'linuxAIO.sh' as 'linuxAIO.sh.old'..."
             mv linuxAIO.sh linuxAIO.sh.old
@@ -89,9 +90,9 @@ linuxAIO_update() {
             mv linuxAIO linuxAIO.old
         fi
 
-        curl -O "$_RAW_URL"/linuxAIO && sudo chmod +x linuxAIO
-        echo "${_CYAN}NOT applying existing configurations to 'linuxAIO'"
-        echo "${_GREEN}Successfully downloaded the newest version of 'linuxAIO'.${_NC}"
+        curl -O "$E_RAW_URL"/linuxAIO && sudo chmod +x linuxAIO
+        echo "${E_CYAN}NOT applying existing configurations to 'linuxAIO'"
+        echo "${E_GREEN}Successfully downloaded the newest version of 'linuxAIO'.${E_NC}"
     ## Download the newest version of 'linuxAIO' and apply existing changes to it.
     else
         ## Save the values of the current Configuration Variables specified in
@@ -102,10 +103,10 @@ linuxAIO_update() {
         installer_branch_found="$?"
         local bot_install_version
         local bot_install_version_found
-        bot_install_version=$(grep '^export _BOT_INSTALL_VERSION=.*' linuxAIO)
+        bot_install_version=$(grep '^export E_BOT_INSTALL_VERSION=.*' linuxAIO)
         bot_install_version_found="$?"
 
-        curl -O "$_RAW_URL"/linuxAIO && sudo chmod +x linuxAIO
+        curl -O "$E_RAW_URL"/linuxAIO && sudo chmod +x linuxAIO
 
         echo "Applying existing configurations to the new 'linuxAIO'..."
 
@@ -115,10 +116,10 @@ linuxAIO_update() {
 
         # Set $bot_install_version inside of the new 'linuxAIO'.
         [[ $bot_install_version_found = 0 ]] \
-            && sed -i "s/^export _BOT_INSTALL_VERSION=.*/$bot_install_version/" linuxAIO
+            && sed -i "s/^export E_BOT_INSTALL_VERSION=.*/$bot_install_version/" linuxAIO
 
-        echo "${_GREEN}Successfully downloaded the newest version of 'linuxAIO' and" \
-            "applied changes to the newest version of 'linuxAIO'${_NC}"
+        echo "${E_GREEN}Successfully downloaded the newest version of 'linuxAIO' and" \
+            "applied changes to the newest version of 'linuxAIO'${E_NC}"
     fi
 
     clean_up "0" "Exiting" "true"
@@ -132,11 +133,11 @@ linuxAIO_update() {
 #   None
 ########
 unsupported() {
-    echo "${_RED}Your operating system is not OFFICIALLY supported for the" \
+    echo "${E_RED}Your operating system is not OFFICIALLY supported for the" \
         "installation, setup, and/or use of NadekoBot" >&2
-    echo "${_YELLOW}WARNING: By continuing, you accept that unexpected behaviors" \
+    echo "${E_YELLOW}WARNING: By continuing, you accept that unexpected behaviors" \
         "may occur. If you run into any errors or problems with the installation and" \
-        "use of the NadekoBot, you are on your own.${_NC}"
+        "use of the NadekoBot, you are on your own.${E_NC}"
     read -rp "Would you like to continue anyways? [y/N] " choice
 
     choice=$(echo "$choice" | tr '[:upper:]' '[:lower:]')
@@ -167,7 +168,7 @@ clean_up() {
     else                     echo -e "\nCleaning up..."
     fi
 
-    cd "$_WORKING_DIR" || _STDERR "Failed to move to NadekoBot's root directory" "1"
+    cd "$E_WORKING_DIR" || E_STDERR "Failed to move to NadekoBot's root directory" "1"
     [[ -d nadekobot_tmp ]] && rm -rf nadekobot_tmp
 
     for file in "${installer_files[@]}"; do
@@ -185,7 +186,7 @@ clean_up() {
 #   None
 ########
 execute_main_installer() {
-    _DOWNLOAD_SCRIPT "$main_installer" "true"
+    E_DOWNLOAD_SCRIPT "$main_installer" "true"
     ./"$main_installer"
     clean_up "$?" "Exiting"
 }
@@ -203,9 +204,9 @@ execute_main_installer() {
 #   $2 - optional
 #       True if the script should output text indicating $1 is being downloaded.
 ########
-_DOWNLOAD_SCRIPT() {
+E_DOWNLOAD_SCRIPT() {
     [[ $2 = true ]] && printf "Downloading '%s'..." "$1"
-    curl -O -s "$_RAW_URL"/"$1"
+    curl -O -s "$E_RAW_URL"/"$1"
     sudo chmod +x "$1"
 }
 
@@ -220,8 +221,8 @@ _DOWNLOAD_SCRIPT() {
 #   $3 - optional
 #       If provided, output an additional message.
 ########
-_STDERR() {
-    echo "${_RED}$1${_NC}" >&2
+E_STDERR() {
+    echo "${E_RED}$1${E_NC}" >&2
     [[ $3 ]] && echo -e "$3"
     [[ $2 ]] && exit "$2"
 }
@@ -247,20 +248,20 @@ trap 'clean_up "148" "Exiting" "true"' SIGTSTP
 
 # If the current 'linuxAIO' revision number is not of equil value of the expected
 # revision number...
-if [[ $_LINUXAIO_REVISION && $_LINUXAIO_REVISION != "$current_linuxAIO_revision" ]]; then
+if [[ $E_LINUXAIO_REVISION && $E_LINUXAIO_REVISION != "$current_linuxAIO_revision" ]]; then
     linuxAIO_update
     clean_up "0" "Exiting"
 fi
 
 # Change the working directory to the location of the executed script.
 cd "${0%/*}" || {
-    echo "${_RED}Failed to change working directory" >&2
-    echo "${_CYAN}Change your working directory to that of the executed script${_NC}"
+    echo "${E_RED}Failed to change working directory" >&2
+    echo "${E_CYAN}Change your working directory to that of the executed script${E_NC}"
     clean_up "1" "Exiting"
 }
 
-export _WORKING_DIR="$PWD"
-export _INSTALLER_PREP="$_WORKING_DIR/installer-prep"
+export E_WORKING_DIR="$PWD"
+export E_INSTALLER_PREP="$E_WORKING_DIR/installer-prep"
 
 
 #### End of [ Prepping ]
@@ -271,31 +272,31 @@ export _INSTALLER_PREP="$_WORKING_DIR/installer-prep"
 clear -x
 
 detect_sys_info
-export _DISTRO _SVER _VER _ARCH
-export -f _DOWNLOAD_SCRIPT _STDERR
+export E_DISTRO E_SVER E_VER E_ARCH
+export -f E_DOWNLOAD_SCRIPT E_STDERR
 
-# Use $_DISTRO if $pname is unset or null...
+# Use $E_DISTRO if $pname is unset or null...
 echo "SYSTEM INFO
 Bit Type: $bits
-Architecture: $_ARCH
-Distro: ${pname:=$_DISTRO}
-Distro Version: $_VER
+Architecture: $E_ARCH
+Distro: ${pname:=$E_DISTRO}
+Distro Version: $E_VER
 "
 
 ### Check if the operating system is supported by NadekoBot and the installer.
 if [[ $bits = 64 ]]; then
-    if [[ $_DISTRO = "ubuntu" ]]; then
-        case "$_VER" in
+    if [[ $E_DISTRO = "ubuntu" ]]; then
+        case "$E_VER" in
             22.04|20.04|18.04) execute_main_installer ;;
             *)                 unsupported ;;
         esac
-    elif [[ $_DISTRO = "debian" ]]; then
-        case "$_SVER" in
+    elif [[ $E_DISTRO = "debian" ]]; then
+        case "$E_SVER" in
             11|10) execute_main_installer ;;
             *)     unsupported ;;
         esac
-    elif [[ $_DISTRO = "linuxmint" ]]; then
-        case "$_SVER" in
+    elif [[ $E_DISTRO = "linuxmint" ]]; then
+        case "$E_SVER" in
             21|20) execute_main_installer ;;
             *)     unsupported ;;
         esac
diff --git a/nadeko-main-installer b/nadeko-main-installer
--- a/nadeko-main-installer
+++ b/nadeko-main-installer
@@ -11,8 +11,8 @@
 
 
 ## To be exported.
-_SERVICE_NAME="nadeko.service"
-_SERVICE="/etc/systemd/system/$_SERVICE_NAME"
+E_SERVICE_NAME="nadeko.service"
+E_SERVICE="/etc/systemd/system/$E_SERVICE_NAME"
 
 # Indicates which major version of .NET is required.
 req_dotnet_version=6
@@ -56,7 +56,7 @@ hash_ccze() {
 #   None
 ########
 disabled_reasons() {
-    echo "${_CYAN}Reasons for the disabled option:"
+    echo "${E_CYAN}Reasons for the disabled option:"
 
     if (! hash dotnet \
             || ! hash redis-server \
@@ -77,7 +77,7 @@ disabled_reasons() {
         echo "    Use option 1 to download NadekoBot"
     fi
 
-    echo "$_NC"
+    echo "$E_NC"
 }
 
 ########################################################################################
@@ -85,13 +85,13 @@ disabled_reasons() {
 
 
 ########
-# Store the status of NadekoBot's service, inside of $_SERVICE_STATUS.
+# Store the status of NadekoBot's service, inside of $E_SERVICE_STATUS.
 #
 # Arguments:
 #   None
 ########
-_GET_SERVICE_STATUS() {
-    _SERVICE_STATUS=$(systemctl is-active "$_SERVICE_NAME")
+E_GET_SERVICE_STATUS() {
+    E_SERVICE_STATUS=$(systemctl is-active "$E_SERVICE_NAME")
 }
 
 ########
@@ -103,20 +103,20 @@ _GET_SERVICE_STATUS() {
 #       stopped or is currently not running.
 #
 # Returns:
-#   1 - If $_SERVICE_NAME is not currently running.
+#   1 - If $E_SERVICE_NAME is not currently running.
 ########
-_STOP_SERVICE() {
-    if [[ $_SERVICE_STATUS = "active" ]]; then
-        echo "Stopping '$_SERVICE_NAME'..."
-        sudo systemctl stop "$_SERVICE_NAME" || {
-            echo "${_RED}Failed to stop '$_SERVICE_NAME'" >&2
-            echo "${_CYAN}You will need to restart '$_SERVICE_NAME' to apply any" \
-                "updates to NadekoBot${_NC}"
+E_STOP_SERVICE() {
+    if [[ $E_SERVICE_STATUS = "active" ]]; then
+        echo "Stopping '$E_SERVICE_NAME'..."
+        sudo systemctl stop "$E_SERVICE_NAME" || {
+            echo "${E_RED}Failed to stop '$E_SERVICE_NAME'" >&2
+            echo "${E_CYAN}You will need to restart '$E_SERVICE_NAME' to apply any" \
+                "updates to NadekoBot${E_NC}"
             return 1
         }
-        [[ $1 = true ]] && echo -e "\n${_GREEN}NadekoBot has been stopped${_NC}"
+        [[ $1 = true ]] && echo -e "\n${E_GREEN}NadekoBot has been stopped${E_NC}"
     else
-        [[ $1 = true ]] && echo -e "\n${_CYAN}NadekoBot is not currently running${_NC}"
+        [[ $1 = true ]] && echo -e "\n${E_CYAN}NadekoBot is not currently running${E_NC}"
     fi
 }
 
@@ -126,36 +126,36 @@ _STOP_SERVICE() {
 # Arguments:
 #   None
 ########
-_FOLLOW_SERVICE_LOGS() {
+E_FOLLOW_SERVICE_LOGS() {
     (
         trap 'exit 130' SIGINT
-        sudo journalctl --no-hostname -f -u "$_SERVICE_NAME"  | ccze -A
+        sudo journalctl --no-hostname -f -u "$E_SERVICE_NAME"  | ccze -A
     )
 }
 
 ########
 # Output additional information to go along with the output of the function
-# '_FOLLOW_SERVICE_LOGS'.
+# 'E_FOLLOW_SERVICE_LOGS'.
 #
 # Arguments:
 #   $1 - required
 #       Indicates if the function was called from one of the runner scripts or from
 #       within the main installer.
 ########
-_WATCH_SERVICE_LOGS() {
+E_WATCH_SERVICE_LOGS() {
     if [[ $1 = "runner" ]]; then
-        echo "Displaying '$_SERVICE_NAME' startup logs, live..."
+        echo "Displaying '$E_SERVICE_NAME' startup logs, live..."
     elif [[ $1 = "opt_five" ]]; then
-        echo "Watching '$_SERVICE_NAME' logs, live..."
+        echo "Watching '$E_SERVICE_NAME' logs, live..."
     else
-        _STDERR "INTERNAL ERROR: Invalid argument for '_WATCH_SERVICE_LOGS': $1" "4"
+        E_STDERR "INTERNAL ERROR: Invalid argument for 'E_WATCH_SERVICE_LOGS': $1" "4"
     fi
 
-    echo "${_CYAN}To stop displaying the startup logs:"
-    echo "1) Press 'Ctrl' + 'C'${_NC}"
+    echo "${E_CYAN}To stop displaying the startup logs:"
+    echo "1) Press 'Ctrl' + 'C'${E_NC}"
     echo ""
 
-    _FOLLOW_SERVICE_LOGS
+    E_FOLLOW_SERVICE_LOGS
 
     [[ $1 = "runner" ]] && echo -e "\nPlease check the logs above to make sure that" \
         "there aren't any errors, and if there are, to resolve whatever issue is" \
@@ -173,7 +173,7 @@ _WATCH_SERVICE_LOGS() {
 #### [ Main ]
 
 
-printf "%sWelcome to the NadekoBot installer menu\n\n" "$_CLRLN"
+printf "%sWelcome to the NadekoBot installer menu\n\n" "$E_CLRLN"
 
 while true; do
     ####################################################################################
@@ -194,7 +194,7 @@ while true; do
     opt_three_text="3. Run NadekoBot in the background with auto restart"
     ## Option 5.
     opt_five_dis=false
-    opt_five_text="5. Display '$_SERVICE_NAME' logs in follow mode"
+    opt_five_text="5. Display '$E_SERVICE_NAME' logs in follow mode"
     ## Option 7.
     opt_seven_dis=false
     opt_seven_text="7. Back up important files"
@@ -204,7 +204,7 @@ while true; do
     ####################################################################################
     #### [[ Variable Checks ]]
     #### The following variables re-check the status, existence, etc., of some service
-    #### or program, that has the possiblity of changing every time the while loop runs.
+    #### or program, that has the possibility of changing every time the while loop runs.
 
 
     if hash dotnet &>/dev/null; then
@@ -218,7 +218,7 @@ while true; do
     #### [[ Main Continued ]]
 
 
-    _GET_SERVICE_STATUS
+    E_GET_SERVICE_STATUS
     hash_ccze
 
     ## Disable option 1 if any of the following tools are not installed.
@@ -228,37 +228,37 @@ while true; do
             || ! "$ccze_installed" \
             || [[ ${dotnet_version:-false} != "$req_dotnet_version" ]]) &>/dev/null; then
         opt_one_dis=true
-        opt_one_text="${_GREY}${opt_one_text}${dis_option}${_NC}"
+        opt_one_text="${E_GREY}${opt_one_text}${dis_option}${E_NC}"
     fi
 
     ## Disable options 2, 3, and 5 if any of the tools in the previous if statement are
     ## not installed, or none of the specified directories/files could be found.
     if "$opt_one_dis" || [[ ! -f nadekobot/output/creds.yml ]]; then
         opt_two_and_three_dis=true
-        opt_two_text="${_GREY}${opt_two_text}${dis_option}${_NC}"
-        opt_three_text="${_GREY}${opt_three_text}${dis_option}${_NC}"
+        opt_two_text="${E_GREY}${opt_two_text}${dis_option}${E_NC}"
+        opt_three_text="${E_GREY}${opt_three_text}${dis_option}${E_NC}"
         opt_five_dis=true
-        opt_five_text="${_GREY}${opt_five_text}${dis_opt_v2}${_NC}"
+        opt_five_text="${E_GREY}${opt_five_text}${dis_opt_v2}${E_NC}"
 
         if [[ ! -d nadekobot ]]; then
             opt_seven_dis=true
-            opt_seven_text="${_GREY}${opt_seven_text}${dis_option}${_NC}"
+            opt_seven_text="${E_GREY}${opt_seven_text}${dis_option}${E_NC}"
         fi
     ## Options 2 and 3 remain enabled, if 'NadekoRun' exists.
     elif [[ -f NadekoRun ]]; then
         ## Option 5 remains enabled, if NadekoBot's service is running.
-        if [[ $_SERVICE_STATUS = "active" ]]; then
-            run_mode_status=" ${_GREEN}(Running in this mode)${_NC}"
+        if [[ $E_SERVICE_STATUS = "active" ]]; then
+            run_mode_status=" ${E_GREEN}(Running in this mode)${E_NC}"
         ## Disable option 5 if NadekoBot's service NOT running.
-        elif [[ $_SERVICE_STATUS = "inactive" ]]; then
+        elif [[ $E_SERVICE_STATUS = "inactive" ]]; then
             opt_five_dis=true
-            opt_five_text="${_GREY}${opt_five_text}${dis_opt_v2}${_NC}"
-            run_mode_status=" ${_YELLOW}(Set up to run in this mode)${_NC}"
+            opt_five_text="${E_GREY}${opt_five_text}${dis_opt_v2}${E_NC}"
+            run_mode_status=" ${E_YELLOW}(Set up to run in this mode)${E_NC}"
         ## Disable option 5.
         else
             opt_five_dis=true
-            opt_five_text="${_GREY}${opt_five_text}${dis_opt_v2}${_NC}"
-            run_mode_status=" ${_YELLOW}(Status unknown)${_NC}"
+            opt_five_text="${E_GREY}${opt_five_text}${dis_opt_v2}${E_NC}"
+            run_mode_status=" ${E_YELLOW}(Status unknown)${E_NC}"
         fi
 
         ## If NadekoBot is running in the background with auto restart...
@@ -271,7 +271,7 @@ while true; do
     ## Options 2 and 3 remained enabled, but option 5 becomes disabled.
     else
         opt_five_dis=true
-        opt_five_text="${_GREY}${opt_five_text}${dis_opt_v2}${_NC}"
+        opt_five_text="${E_GREY}${opt_five_text}${dis_opt_v2}${E_NC}"
     fi
 
     echo "$opt_one_text"
@@ -288,17 +288,17 @@ while true; do
             ## B.1.
             if "$opt_one_dis"; then
                 clear -x
-                echo "${_RED}Option 1 is currently disabled${_NC}"
+                echo "${E_RED}Option 1 is currently disabled${E_NC}"
                 disabled_reasons
                 continue
             fi
 
-            export _SERVICE
-            export -f _STOP_SERVICE
-            export _SERVICE_NAME
-            export _SERVICE_STATUS
+            export E_SERVICE
+            export -f E_STOP_SERVICE
+            export E_SERVICE_NAME
+            export E_SERVICE_STATUS
 
-            _DOWNLOAD_SCRIPT "nadeko-latest-installer" "true"
+            E_DOWNLOAD_SCRIPT "nadeko-latest-installer" "true"
             clear -x
             ./nadeko-latest-installer || exit_code_actions "$?"
 
@@ -308,33 +308,33 @@ while true; do
             # TODO: Re-due comments...
             # Execute the newly downloaded version of 'installer-prep', so that all
             # changes are applied.
-            exec "$_INSTALLER_PREP"
+            exec "$E_INSTALLER_PREP"
             ;;
         2|3)
             ## B.1.
             if "$opt_two_and_three_dis"; then
                 clear -x
-                echo "${_RED}Option $choice is currently disabled${_NC}"
+                echo "${E_RED}Option $choice is currently disabled${E_NC}"
                 disabled_reasons
                 continue
             fi
 
-            export _SERVICE
-            export _SERVICE_NAME
-            export _SERVICE_STATUS
-            export -f _WATCH_SERVICE_LOGS
-            export -f _FOLLOW_SERVICE_LOGS
+            export E_SERVICE
+            export E_SERVICE_NAME
+            export E_SERVICE_STATUS
+            export -f E_WATCH_SERVICE_LOGS
+            export -f E_FOLLOW_SERVICE_LOGS
 
-            _DOWNLOAD_SCRIPT "nadeko-runner"
+            E_DOWNLOAD_SCRIPT "nadeko-runner"
             clear -x
 
             # If option 2 was executed...
             if [[ $choice = 2 ]]; then
-                export _CODENAME="NadekoRun"
+                export E_CODENAME="NadekoRun"
                 printf "We will now run NadekoBot in the background. "
             # If option 3 was executed...
             else
-                export _CODENAME="NadekoRunAR"
+                export E_CODENAME="NadekoRunAR"
                 printf "We will now run NadekoBot in the background with auto restart. "
             fi
 
@@ -345,7 +345,7 @@ while true; do
         4)
             clear -x
             read -rp "We will now stop NadekoBot. Press [Enter] to begin."
-            _STOP_SERVICE "true"
+            E_STOP_SERVICE "true"
             read -rp "Press [Enter] to return to the installer menu"
             clear -x
             ;;
@@ -353,16 +353,16 @@ while true; do
             clear -x
             ## B.1.
             if "$opt_five_dis"; then
-                echo "${_RED}Option 5 is currently disabled${_NC}"
+                echo "${E_RED}Option 5 is currently disabled${E_NC}"
                 echo ""
                 continue
             fi
 
-            _WATCH_SERVICE_LOGS "opt_five"
+            E_WATCH_SERVICE_LOGS "opt_five"
             clear -x
             ;;
         6)
-            _DOWNLOAD_SCRIPT "prereqs-installer"
+            E_DOWNLOAD_SCRIPT "prereqs-installer"
             clear -x
             ./prereqs-installer || exit_code_actions "$?"
             clear -x
@@ -371,12 +371,12 @@ while true; do
             ## B.1.
             if "$opt_seven_dis"; then
                 clear -x
-                echo "${_RED}Option 7 is currently disabled${_NC}"
+                echo "${E_RED}Option 7 is currently disabled${E_NC}"
                 disabled_reasons
                 continue
             fi
 
-            _DOWNLOAD_SCRIPT "file-backup"
+            E_DOWNLOAD_SCRIPT "file-backup"
             clear -x
             ./file-backup || exit_code_actions "$?"
             clear -x
@@ -386,7 +386,7 @@ while true; do
             ;;
         *)
             clear -x
-            echo "${_RED}Invalid input: '$choice' is not a valid option${_NC}" >&2
+            echo "${E_RED}Invalid input: '$choice' is not a valid option${E_NC}" >&2
             echo ""
             ;;
     esac
diff --git a/nadeko-runner b/nadeko-runner
--- a/nadeko-runner
+++ b/nadeko-runner
@@ -11,7 +11,7 @@
 
 
 ### Indicate which actions to be performed on NadekoBot's service.
-if [[ $_CODENAME = "NadekoRun" ]]; then
+if [[ $E_CODENAME = "NadekoRun" ]]; then
     lower="disable"    # A.1.
     upper="Disabling"  # B.1.
 else
@@ -37,7 +37,7 @@ StartLimitBurst=2
 [Service]
 Type=simple
 User=$USER
-WorkingDirectory=$_WORKING_DIR
+WorkingDirectory=$E_WORKING_DIR
 ExecStart=/bin/bash NadekoRun
 Restart=on-failure
 RestartSec=5
@@ -57,7 +57,7 @@ StartLimitBurst=2
 [Service]
 Type=simple
 User=$USER
-WorkingDirectory=$_WORKING_DIR
+WorkingDirectory=$E_WORKING_DIR
 ExecStart=/bin/bash NadekoRun
 Restart=on-failure
 RestartSec=5
@@ -76,26 +76,26 @@ fi
 
 
 # Check if the service exists.
-if [[ -f $_SERVICE ]]; then echo "Updating '$_SERVICE_NAME'..."
-else                        echo "Creating '$_SERVICE_NAME'..."
+if [[ -f $E_SERVICE ]]; then echo "Updating '$E_SERVICE_NAME'..."
+else                        echo "Creating '$E_SERVICE_NAME'..."
 fi
 
 {
     # Create/update the service.
-    echo "$service_content" | sudo tee "$_SERVICE" &>/dev/null \
+    echo "$service_content" | sudo tee "$E_SERVICE" &>/dev/null \
         && sudo systemctl daemon-reload
 } || {
-    echo "${_RED}Failed to create '$_SERVICE_NAME'" >&2
-    echo "${_CYAN}This service must exist for NadekoBot to work${_NC}"
+    echo "${E_RED}Failed to create '$E_SERVICE_NAME'" >&2
+    echo "${E_CYAN}This service must exist for NadekoBot to work${E_NC}"
     read -rp "Press [Enter] to return to the installer menu"
     exit 3
 }
 
 ## Disable/enable the service.
-echo "$upper '$_SERVICE_NAME'..."
-sudo systemctl "$lower" "$_SERVICE_NAME" || {
-    echo "${_RED}Failed to $lower '$_SERVICE_NAME'" >&2
-    echo "${_CYAN}This service must be ${lower}d in order to use this run mode${_NC}"
+echo "$upper '$E_SERVICE_NAME'..."
+sudo systemctl "$lower" "$E_SERVICE_NAME" || {
+    echo "${E_RED}Failed to $lower '$E_SERVICE_NAME'" >&2
+    echo "${E_CYAN}This service must be ${lower}d in order to use this run mode${E_NC}"
     read -rp "Press [Enter] to return to the installer menu"
     exit 3
 }
@@ -111,7 +111,7 @@ else
 fi
 
 ## Add the code required to run NadekoBot in the background, to 'NadekoRun'.
-if [[ $_CODENAME = "NadekoRun" ]]; then
+if [[ $E_CODENAME = "NadekoRun" ]]; then
     printf '%s\n' \
         "#!/bin/bash" \
         "" \
@@ -121,14 +121,14 @@ if [[ $_CODENAME = "NadekoRun" ]]; then
         "youtube-dl -U" \
         "" \
         "echo \"Starting NadekoBot...\"" \
-        "cd $_WORKING_DIR/nadekobot/output" \
+        "cd $E_WORKING_DIR/nadekobot/output" \
         "dotnet NadekoBot.dll || {" \
         "    echo \"An error occurred when trying to start NadekoBot\"" \
         "    echo \"Exiting...\"" \
         "    exit 1" \
         "}" \
         "echo \"Stopping NadekoBot...\"" \
-        "cd $_WORKING_DIR" > NadekoRun
+        "cd $E_WORKING_DIR" > NadekoRun
 ## Add code required to run NadekoBot in the background with auto restart, to
 ## 'NadekoRun'.
 else
@@ -143,15 +143,15 @@ else
         "echo \"Starting NadekoBot...\"" \
         "" \
         "while true; do" \
-        "    if [[ -d $_WORKING_DIR/nadekobot/output ]]; then" \
-        "        cd $_WORKING_DIR/nadekobot/output || {" \
-        "            echo \"Failed to change working directory to '$_WORKING_DIR/nadekobot/output'\" >&2" \
+        "    if [[ -d $E_WORKING_DIR/nadekobot/output ]]; then" \
+        "        cd $E_WORKING_DIR/nadekobot/output || {" \
+        "            echo \"Failed to change working directory to '$E_WORKING_DIR/nadekobot/output'\" >&2" \
         "            echo \"Ensure that the working directory inside of '/etc/systemd/system/nadeko.service' is correct\"" \
         "            echo \"Exiting...\"" \
         "            exit 1" \
         "        }" \
         "    else" \
-        "        echo \"'$_WORKING_DIR/nadekobot/output' doesn't exist\"" \
+        "        echo \"'$E_WORKING_DIR/nadekobot/output' doesn't exist\"" \
         "        exit 1" \
         "    fi" \
         "" \
@@ -171,24 +171,24 @@ else
 fi
 
 ## Restart the service if it is currently running.
-if [[ $_SERVICE_STATUS = "active" ]]; then
-    echo "Restarting '$_SERVICE_NAME'..."
-    sudo systemctl restart "$_SERVICE_NAME" || {
-        echo "${_RED}Failed to restart '$_SERVICE_NAME'${_NC}" >&2
+if [[ $E_SERVICE_STATUS = "active" ]]; then
+    echo "Restarting '$E_SERVICE_NAME'..."
+    sudo systemctl restart "$E_SERVICE_NAME" || {
+        echo "${E_RED}Failed to restart '$E_SERVICE_NAME'${E_NC}" >&2
         read -rp "Press [Enter] to return to the installer menu"
         exit 3
     }
 ## Start the service if it is NOT currently running.
 else
-    echo "Starting '$_SERVICE_NAME'..."
-    sudo systemctl start "$_SERVICE_NAME" || {
-        echo "${_RED}Failed to start '$_SERVICE_NAME'${_NC}" >&2
+    echo "Starting '$E_SERVICE_NAME'..."
+    sudo systemctl start "$E_SERVICE_NAME" || {
+        echo "${E_RED}Failed to start '$E_SERVICE_NAME'${E_NC}" >&2
         read -rp "Press [Enter] to return to the installer menu"
         exit 3
     }
 fi
 
-_WATCH_SERVICE_LOGS "runner"
+E_WATCH_SERVICE_LOGS "runner"
 
 
 #### End of [ Variables ]
