Improve documentation, comments, and syntax

diff --git a/installer-prep b/installer-prep
--- a/installer-prep
+++ b/installer-prep
@@ -1,43 +1,35 @@
 #!/bin/bash
 #
-# This script looks at the operating system, architecture, bit type, etc., to determine
-# whether or not the system is supported by NadekoBot. Once the system is deemed as
-# supported, the main installer will be downloaded and executed.
+# This script checks the operating system, architecture, bit type, and other factors to
+# determine if the system is compatible with NadekoBot. If the system is supported, it
+# will download and execute the main installer.
 #
 ########################################################################################
-####[ Exported and/or Globally Used Variables ]#########################################
+####[ Exported and Global Variables ]###################################################
 
 
 # Refer to the 'README' note at the beginning of 'linuxAIO' for more information.
-current_linuxAIO_revision=39
-# Name of the main installer script.
-main_installer="nadeko-main-installer"
+readonly C_CURRENT_LINUXAIO_REVISION=39
+readonly C_MAIN_INSTALLER="nadeko-main-installer"
 
 ## Modify output text color.
-# shellcheck disable=SC2155
-{
-    export E_YELLOW="$(printf '\033[1;33m')"
-    export E_GREEN="$(printf '\033[0;32m')"
-    export E_CYAN="$(printf '\033[0;36m')"
-    export E_RED="$(printf '\033[1;31m')"
-    export E_NC="$(printf '\033[0m')"
-    export E_GREY="$(printf '\033[0;90m')"
-    export E_CLRLN="$(printf '\r\033[K')"
-}
+E_YELLOW="$(printf '\033[1;33m')"
+E_GREEN="$(printf '\033[0;32m')"
+E_CYAN="$(printf '\033[0;36m')"
+E_RED="$(printf '\033[1;31m')"
+E_NC="$(printf '\033[0m')"
+E_GREY="$(printf '\033[0;90m')"
+E_CLRLN="$(printf '\r\033[K')"
+export E_YELLOW E_GREEN E_CYAN E_RED E_NC E_GREY E_CLRLN
 
 
 ####[ Functions ]#######################################################################
 
 
-########
+####
 # Identify the operating system, version number, architecture, bit type (32 or 64), etc.
-#
-# Arguments:
-#   None
-########
 detect_sys_info() {
     if [[ -f /etc/os-release ]]; then
-        # shellcheck disable=SC1091
         . /etc/os-release
         E_DISTRO="$ID"
         E_VER="$VERSION_ID"  # Version: x.x.x...
@@ -48,7 +40,6 @@ detect_sys_info() {
         E_VER=$(uname -r)
     fi
 
-    ## Identify bit and architecture type.
     case $(uname -m) in
         x86_64) bits="64"; E_ARCH="x64" ;;
         i*86)   bits="32"; E_ARCH="x86" ;;
@@ -57,13 +48,9 @@ detect_sys_info() {
     esac
 }
 
-########
+####
 # Download the latest version of 'linuxAIO' if $E_LINUXAIO_REVISION and
-# $current_linuxAIO_revision aren't of equal value.
-#
-# Arguments:
-#  None
-########
+# $C_CURRENT_LINUXAIO_REVISION aren't of equal value.
 linuxAIO_update() {
     echo -n "${E_YELLOW}You are using an older version of 'linuxAIO'. "
     read -rp "Press [Enter] to download the latest version.${E_NC}"
@@ -74,11 +61,9 @@ linuxAIO_update() {
     ## configurations will not be applied to the newest version of 'linuxAIO', and the
     ## end-user will have to reconfigure 'linuxAIO' manually.
     ##
-    ## NOTE:
-    ##  $_LINUXAIO_REVISION and $_RAW_URL are from revision 38 and below. This means
-    ##  that the if statement doesn't need to test for $E_LINUXAIO_REVISION.
-    ##
     # shellcheck disable=SC2153
+    #   $_LINUXAIO_REVISION and $_RAW_URL are from revision 38 and earlier. This means
+    #   that the if statement doesn't need to test for $E_LINUXAIO_REVISION.
     if ((_LINUXAIO_REVISION <= 38)); then
         if [[ -f linuxAIO.sh ]]; then
             echo "Backing up 'linuxAIO.sh' as 'linuxAIO.sh.old'..."
@@ -93,8 +78,6 @@ linuxAIO_update() {
         echo "${E_GREEN}Successfully downloaded the newest version of 'linuxAIO'.${E_NC}"
     ## Download the newest version of 'linuxAIO' and apply existing changes to it.
     else
-        ## Save the values of the current Configuration Variables specified in
-        ## 'linuxAIO', to be set in the new 'linuxAIO'.
         local installer_branch
         local installer_branch_found
         installer_branch=$(grep '^installer_branch=.*' linuxAIO)
@@ -108,28 +91,22 @@ linuxAIO_update() {
 
         echo "Applying existing configurations to the new 'linuxAIO'..."
 
-        # Set $installer_branch inside of the new 'linuxAIO'.
-        [[ $installer_branch_found = 0 ]] \
+        [[ $installer_branch_found == 0 ]] \
             && sed -i "s/^installer_branch=.*/$installer_branch/" linuxAIO
 
-        # Set $bot_install_version inside of the new 'linuxAIO'.
-        [[ $bot_install_version_found = 0 ]] \
+        [[ $bot_install_version_found == 0 ]] \
             && sed -i "s/^export E_BOT_INSTALL_VERSION=.*/$bot_install_version/" linuxAIO
 
         echo "${E_GREEN}Successfully downloaded the newest version of 'linuxAIO' and" \
-            "applied changes to the newest version of 'linuxAIO'${E_NC}"
+            "applied existing changes${E_NC}"
     fi
 
     clean_up "0" "Exiting" "true"
 }
 
-########
+####
 # Provide the end-user with the option to continue, even if their system isn't
 # officially supported.
-#
-# Arguments:
-#   None
-########
 unsupported() {
     echo "${E_RED}Your operating system is not OFFICIALLY supported for the" \
         "installation, setup, and/or use of NadekoBot" >&2
@@ -138,32 +115,42 @@ unsupported() {
         "use of the NadekoBot, you are on your own.${E_NC}"
     read -rp "Would you like to continue anyways? [y/N] " choice
 
-    choice=$(echo "$choice" | tr '[:upper:]' '[:lower:]')
+    choice=${choice,,}
     case "$choice" in
-        y|yes) clear -x; execute_main_installer ;;
-        *)     clean_up "0" "Exiting" ;;
+        y|yes)
+            clear -x
+            execute_main_installer
+            ;;
+        *)
+            clean_up "0" "Exiting"
+            ;;
     esac
 }
 
-########
+####
 # Cleanly exit the installer by removing files that aren't required unless the installer
 # is currently running.
 #
-# Arguments:
-#   $1 - required
+# PARAMETERS:
+#   - $1: exit_code (Required)
 #       Exit code.
-#   $2 - required
+#   - $2: output_text (Required)
 #       Output text.
-#   $3 - optional
+#   - $3: clean_up_text (Optional, Default: false)
 #       True if 'Cleaning up...' should be printed with two new-line symbols.
-########
 clean_up() {
+    local exit_code="$1"
+    local output_text="$2"
+    local clean_up_text="${3:-false}"
+
     # Files to be removed.
     local installer_files=("installer-prep" "file-backup" "prereqs-installer"
         "nadeko-latest-installer" "nadeko-runner" "nadeko-main-installer")
 
-    if [[ $3 = true ]]; then echo -e "\n\nCleaning up..."
-    else                     echo -e "\nCleaning up..."
+    if [[ $clean_up_text == true ]]; then
+        echo -e "\n\nCleaning up..."
+    else
+        echo -e "\nCleaning up..."
     fi
 
     cd "$E_WORKING_DIR" || E_STDERR "Failed to move to NadekoBot's root directory" "1"
@@ -173,19 +160,15 @@ clean_up() {
         [[ -f $file ]] && rm "$file"
     done
 
-    echo "$2..."
-    exit "$1"
+    echo "$output_text..."
+    exit "$exit_code"
 }
 
-########
-# Download and execute $main_installer.
-#
-# Arguments:
-#   None
-########
+####
+# Download and execute $C_MAIN_INSTALLER.
 execute_main_installer() {
-    E_DOWNLOAD_SCRIPT "$main_installer" "true"
-    ./"$main_installer"
+    E_DOWNLOAD_SCRIPT "$C_MAIN_INSTALLER" "true"
+    ./"$C_MAIN_INSTALLER"
     clean_up "$?" "Exiting"
 }
 
@@ -193,42 +176,49 @@ execute_main_installer() {
 ### [ Functions To Be Exported ]
 ###
 
-########
+####
 # Download the specified script and modify it's execution permissions.
 #
-# Arguments:
-#   $1 - required
+# PARAMETERS:
+#   - $1: script_name (Required)
 #       Name of the script to download.
-#   $2 - optional
+#   - $2: script_output (Optional, Default: false)
 #       True if the script should output text indicating $1 is being downloaded.
-########
 E_DOWNLOAD_SCRIPT() {
-    [[ $2 = true ]] && printf "Downloading '%s'..." "$1"
-    curl -O -s "$E_RAW_URL"/"$1"
-    sudo chmod +x "$1"
+    local script_name="$1"
+    local script_output="${2:-false}"
+
+    [[ $script_output == true ]] && printf "Downloading '%s'..." "$script_name"
+
+    curl -O -s "$E_RAW_URL"/"$script_name"
+    sudo chmod +x "$script_name"
 }
 
-########
+####
 # Output an error message, and if desired, exit the script.
 #
-# Arguments:
-#   $1 - required
+# PARAMETERS:
+#   - $1: error_message (Required)
 #       Error message.
-#   $2 - optional
+#   - $2: exit_code (Optional)
 #       If provided, exit with the provided value.
-#   $3 - optional
+#   - $3: additional_message (Optional)
 #       If provided, output an additional message.
-########
 E_STDERR() {
-    echo "${E_RED}$1${E_NC}" >&2
-    [[ $3 ]] && echo -e "$3"
-    [[ $2 ]] && exit "$2"
+    local error_message="$1"
+    local exit_code="${2:-}"
+    local additional_message="${3:-}"
+
+    echo "${E_RED}$error_message${E_NC}" >&2
+    [[ $additional_message ]] && echo -e "$additional_message" >&2
+    [[ $exit_code ]] && exit "$exit_code"
 }
 
 
 ####[ Error Traps ]#####################################################################
 
 
+# TODO: Update with better trapping...
 trap 'clean_up "130" "Exiting" "true"' SIGINT
 trap 'clean_up "143" "Exiting" "true"' SIGTERM
 trap 'clean_up "148" "Exiting" "true"' SIGTSTP
@@ -237,11 +227,9 @@ trap 'clean_up "148" "Exiting" "true"' SIGTSTP
 ####[ Prepping ]########################################################################
 
 
-# If the current 'linuxAIO' revision number is not of equil value of the expected
-# revision number...
-if [[ $E_LINUXAIO_REVISION && $E_LINUXAIO_REVISION != "$current_linuxAIO_revision" ]]; then
+if [[ $E_LINUXAIO_REVISION != "$C_CURRENT_LINUXAIO_REVISION" ]]; then
+    # NOTE: Script will exit after updating 'linuxAIO'.
     linuxAIO_update
-    clean_up "0" "Exiting"
 fi
 
 # Change the working directory to the location of the executed script.
diff --git a/nadeko-main-installer b/nadeko-main-installer
--- a/nadeko-main-installer
+++ b/nadeko-main-installer
@@ -3,8 +3,8 @@
 # The main installer for Linux.
 #
 # Comment Key:
-#   A.1. - Return to prevent further code execution.
-#   B.1. - Prevent the code from running if the option is disabled.
+#   A.1.: Return to prevent further code execution.
+#   B.1.: Prevent the code from running if the option is disabled.
 #
 ########################################################################################
 ####[ Variables ]#######################################################################
@@ -14,53 +14,48 @@
 E_SERVICE_NAME="nadeko.service"
 E_SERVICE="/etc/systemd/system/$E_SERVICE_NAME"
 
-# Indicates which major version of .NET is required.
-req_dotnet_version=6
+readonly C_REQ_DOTNET_VERSION=6
 
 
 ####[ Functions ]#######################################################################
 
 
-########
+####
 # Depending on the return/exit code from any of the executed scripts, perform the
 # corresponding/appropriate actions.
 #
 # Arguments:
-#   $1 - required
-#       Return/exit code.
-########
+#   - $1: exit_code (Required)
+#       - Return/exit code.
 exit_code_actions() {
-    case "$1" in
+    local exit_code="$1"
+
+    case "$exit_code" in
         3) return 0 ;;
-        *) exit "$1" ;;
+        *) exit "$exit_code" ;;
     esac
 }
 
-########
+####
 # Return whether or not 'ccze' is installed.
-#
-# Arguments:
-#   None
-########
 hash_ccze() {
-    hash ccze &>/dev/null && ccze_installed=true \
-                          || ccze_installed=false
+    if hash ccze &>/dev/null; then
+        C_CCZE_INSTALLED=true
+    else
+        C_CCZE_INSTALLED=false
+    fi
 }
 
-########
+####
 # Provide the reason(s) for why one or more options are disabled.
-#
-# Arguments:
-#   None
-########
 disabled_reasons() {
     echo "${E_CYAN}Reasons for the disabled option:"
 
     if (! hash dotnet \
             || ! hash redis-server \
             || (! hash python && (! hash python3 && ! hash python-is-python3)) \
-            || ! "$ccze_installed" \
-            || [[ ${dotnet_version:-false} != "$req_dotnet_version" ]]) &>/dev/null; then
+            || ! "$C_CCZE_INSTALLED" \
+            || [[ ${dotnet_version:-false} != "$C_REQ_DOTNET_VERSION" ]]) &>/dev/null; then
         echo "  One or more prerequisites are not installed"
         echo "    Use option 6 to install them all"
     fi
@@ -82,12 +77,8 @@ disabled_reasons() {
 ### [ Functions To Be Exported ]
 ###
 
-########
+####
 # Store the status of NadekoBot's service, inside of $E_SERVICE_STATUS.
-#
-# Arguments:
-#   None
-########
 E_GET_SERVICE_STATUS() {
     E_SERVICE_STATUS=$(systemctl is-active "$E_SERVICE_NAME")
 }
@@ -95,16 +86,17 @@ E_GET_SERVICE_STATUS() {
 ########
 # Stops NadekoBot's service.
 #
-# Arguments:
-#   $1 - optional
-#       True when the function should output text indicating if the service has been
-#       stopped or is currently not running.
+# PARAMETERS:
+#   - $1: output_text (Optional, Default: false)
+#       - True when the function should output text indicating if the service has been
+#         stopped or is currently not running.
 #
-# Returns:
-#   1 - If $E_SERVICE_NAME is not currently running.
-########
+# RETURNS:
+#   - 1: If $E_SERVICE_NAME is not currently running.
 E_STOP_SERVICE() {
-    if [[ $E_SERVICE_STATUS = "active" ]]; then
+    local output_text="${1:-false}"
+
+    if [[ $E_SERVICE_STATUS == "active" ]]; then
         echo "Stopping '$E_SERVICE_NAME'..."
         sudo systemctl stop "$E_SERVICE_NAME" || {
             echo "${E_RED}Failed to stop '$E_SERVICE_NAME'" >&2
@@ -112,18 +104,16 @@ E_STOP_SERVICE() {
                 "updates to NadekoBot${E_NC}"
             return 1
         }
-        [[ $1 = true ]] && echo -e "\n${E_GREEN}NadekoBot has been stopped${E_NC}"
+        [[ $output_text == true ]] \
+            && echo -e "\n${E_GREEN}NadekoBot has been stopped${E_NC}"
     else
-        [[ $1 = true ]] && echo -e "\n${E_CYAN}NadekoBot is not currently running${E_NC}"
+        [[ $output_text == true ]] \
+            && echo -e "\n${E_CYAN}NadekoBot is not currently running${E_NC}"
     fi
 }
 
 ########
 # Display the logs from 'nadeko.server' as they are created.
-#
-# Arguments:
-#   None
-########
 E_FOLLOW_SERVICE_LOGS() {
     (
         trap 'exit 130' SIGINT
@@ -135,15 +125,19 @@ E_FOLLOW_SERVICE_LOGS() {
 # Output additional information to go along with the output of the function
 # 'E_FOLLOW_SERVICE_LOGS'.
 #
-# Arguments:
-#   $1 - required
-#       Indicates if the function was called from one of the runner scripts or from
-#       within the main installer.
-########
+# PARAMETERS:
+#   - $1: log_type (Required)
+#       - Indicates if the function was called from one of the runner scripts or from
+#         within the main installer.
+#       - Acceptable values:
+#           - "runner": Called from one of the runner scripts.
+#           - "opt_five": Called from the main installer.
 E_WATCH_SERVICE_LOGS() {
-    if [[ $1 = "runner" ]]; then
+    local log_type="$1"
+
+    if [[ $log_type == "runner" ]]; then
         echo "Displaying '$E_SERVICE_NAME' startup logs, live..."
-    elif [[ $1 = "opt_five" ]]; then
+    elif [[ $log_type == "opt_five" ]]; then
         echo "Watching '$E_SERVICE_NAME' logs, live..."
     else
         E_STDERR "INTERNAL ERROR: Invalid argument for 'E_WATCH_SERVICE_LOGS': $1" "4"
@@ -155,7 +149,7 @@ E_WATCH_SERVICE_LOGS() {
 
     E_FOLLOW_SERVICE_LOGS
 
-    [[ $1 = "runner" ]] && echo -e "\nPlease check the logs above to make sure that" \
+    [[ $1 == "runner" ]] && echo -e "\nPlease check the logs above to make sure that" \
         "there aren't any errors, and if there are, to resolve whatever issue is" \
         "causing them"
 
@@ -216,8 +210,8 @@ while true; do
     if (! hash dotnet \
             || ! hash redis-server \
             || ! hash python3 \
-            || ! "$ccze_installed" \
-            || [[ ${dotnet_version:-false} != "$req_dotnet_version" ]]) &>/dev/null; then
+            || ! "$C_CCZE_INSTALLED" \
+            || [[ ${dotnet_version:-false} != "$C_REQ_DOTNET_VERSION" ]]) &>/dev/null; then
         opt_one_dis=true
         opt_one_text="${E_GREY}${opt_one_text}${dis_option}${E_NC}"
     fi
diff --git a/nadeko-runner b/nadeko-runner
--- a/nadeko-runner
+++ b/nadeko-runner
@@ -3,8 +3,8 @@
 # Start NadekoBot in a specified run mode.
 #
 # Comment key:
-#   A.1. - Used in conjunction with 'systemctl'.
-#   B.1. - Used in the text output.
+#   A.1.: Used in conjunction with 'systemctl'.
+#   B.1.: Used in the text output.
 #
 ########################################################################################
 ####[ Variables ]#######################################################################
@@ -12,23 +12,21 @@
 
 ### Indicate which actions to be performed on NadekoBot's service.
 if [[ $E_CODENAME = "NadekoRun" ]]; then
-    lower="disable"    # A.1.
-    upper="Disabling"  # B.1.
+    readonly C_LOWER="disable"    # A.1.
+    readonly C_UPPER="Disabling"  # B.1.
 else
-    lower="enable"    # A.1.
-    upper="Enabling"  # B.1.
+    readonly C_LOWER="enable"    # A.1.
+    readonly C_UPPER="Enabling"  # B.1.
 fi
 
-systemd_version_tmp=$(systemd --version)
-# shellcheck disable=SC2206
-systemd_version_tmp=($systemd_version_tmp)
-systemd_version=${systemd_version_tmp[1]}
+systemd_version=$(systemd --version | awk 'NR==1 {print $2}')
 
 ## The contents of NadekoBot's service.
-## NOTE: 'StandardOutput' and 'StandardError' no longer supports 'syslog' starting in
-##       version 246 of systemd.
-if ((systemd_version >= 246)); then
-    service_content="[Unit]
+## NOTE:
+##  'StandardOutput' and 'StandardError' no longer supports 'syslog' starting in
+##  version 246 of systemd.
+if (( systemd_version >= 246)); then
+    readonly C_SERVICE_CONTENT="[Unit]
 Description=NadekoBot service
 After=network.target
 StartLimitIntervalSec=60
@@ -48,7 +46,7 @@ SyslogIdentifier=NadekoBot
 [Install]
 WantedBy=multi-user.target"
 else
-    service_content="[Unit]
+    readonly C_SERVICE_CONTENT="[Unit]
 Description=NadekoBot service
 After=network.target
 StartLimitIntervalSec=60
@@ -69,6 +67,8 @@ SyslogIdentifier=NadekoBot
 WantedBy=multi-user.target"
 fi
 
+unset systemd_version
+
 
 ####[ Main ]############################################################################
 
@@ -80,7 +80,7 @@ fi
 
 {
     # Create/update the service.
-    echo "$service_content" | sudo tee "$E_SERVICE" &>/dev/null \
+    echo "$C_SERVICE_CONTENT" | sudo tee "$E_SERVICE" &>/dev/null \
         && sudo systemctl daemon-reload
 } || {
     echo "${E_RED}Failed to create '$E_SERVICE_NAME'" >&2
@@ -90,10 +90,10 @@ fi
 }
 
 ## Disable/enable the service.
-echo "$upper '$E_SERVICE_NAME'..."
-sudo systemctl "$lower" "$E_SERVICE_NAME" || {
-    echo "${E_RED}Failed to $lower '$E_SERVICE_NAME'" >&2
-    echo "${E_CYAN}This service must be ${lower}d in order to use this run mode${E_NC}"
+echo "$C_UPPER '$E_SERVICE_NAME'..."
+sudo systemctl "$C_LOWER" "$E_SERVICE_NAME" || {
+    echo "${E_RED}Failed to $C_LOWER '$E_SERVICE_NAME'" >&2
+    echo "${E_CYAN}This service must be ${C_LOWER}d in order to use this run mode${E_NC}"
     read -rp "Press [Enter] to return to the installer menu"
     exit 3
 }
@@ -154,7 +154,7 @@ else
         "    fi" \
         "" \
         "    dotnet NadekoBot.dll || {" \
-        "        echo \"An error occurred when trying to start NadekBot\"" \
+        "        echo \"An error occurred when trying to start NadekoBot\"" \
         "        echo \"Exiting...\"" \
         "        exit 1" \
         "    }" \
