refactor: improve logging and error handling in NadekoBot startup scripts
- Added structured log messages with severity levels ([INFO], [ERROR], [WARN], [NOTE]).
- Enhanced error handling with more descriptive messages.
- Improved script readability and maintainability.

diff --git a/nadeko-runner b/nadeko-runner
--- a/nadeko-runner
+++ b/nadeko-runner
@@ -167,63 +167,61 @@ else
     sudo chmod +x NadekoRun
 fi
 
-## Add the code required to run NadekoBot in the background, to 'NadekoRun'.
 if [[ $E_CODENAME == "NadekoRun" ]]; then
     echo "#!/bin/bash
 
 _code_name_=\"NadekoRun\"
 
-echo \"Running NadekoBot in the background\"
-youtube-dl -U
+echo \"[INFO] Running NadekoBot in the background\"
+youtube-dl -U || echo \"[ERROR] Failed to update 'youtube-dl'\" >&2
 
-echo \"Starting NadekoBot...\"
+echo \"[INFO] Starting NadekoBot...\"
 cd $E_ROOT_DIR/nadekobot/output
 dotnet NadekoBot.dll || {
-    echo \"An error occurred when trying to start NadekoBot\"
-    echo \"Exiting...\"
+    echo \"[ERROR] Failed to start NadekoBot\" >&2
+    echo \"[INFO] Exiting...\"
     exit 1
 }
 
-echo \"Stopping NadekoBot...\"
+echo \"[INFO] Stopping NadekoBot...\"
 cd $E_ROOT_DIR" > NadekoRun
-## Add code required to run NadekoBot in the background with auto restart, to
-## 'NadekoRun'.
 else
     echo "#!/bin/bash
 
 _code_name_=\"NadekoRunAR\"
 
-echo \"Running NadekoBot in the background with auto restart\"
-youtube-dl -U
+echo \"[INFO] Running NadekoBot in the background with auto restart\"
+youtube-dl -U || echo \"[ERROR] Failed to update 'youtube-dl'\" >&2
 
-echo \"Starting NadekoBot...\"
+echo \"[INFO] Starting NadekoBot...\"
 
 while true; do
     if [[ -d $E_ROOT_DIR/nadekobot/output ]]; then
         cd $E_ROOT_DIR/nadekobot/output || {
-            echo \"Failed to change working directory to '$E_ROOT_DIR/nadekobot/output'\" >&2
-            echo \"Ensure that the working directory inside of '/etc/systemd/system/nadeko.service' is correct\"
-            echo \"Exiting...\"
+            echo \"[ERROR] Failed to change working directory to '$E_ROOT_DIR/nadekobot/output'\" >&2
+            echo \"[NOTE] Ensure the working directory in '/etc/systemd/system/nadeko.service' is correct\"
+            echo \"[INFO] Exiting...\"
             exit 1
         }
     else
-        echo \"'$E_ROOT_DIR/nadekobot/output' doesn't exist\"
+        echo \"[WARN] '$E_ROOT_DIR/nadekobot/output' doesn't exist\" >&2
+        echo \"[INFO] Exiting...\"
         exit 1
     fi
 
     dotnet NadekoBot.dll || {
-        echo \"An error occurred when trying to start NadekoBot\"
-        echo \"Exiting...\"
+        echo \"[ERROR] An error occurred when trying to start NadekoBot\" >&2
+        echo \"[INFO] Exiting...\"
         exit 1
     }
 
-    echo \"Waiting for 5 seconds...\"
+    echo \"[INFO] Waiting 5 seconds...\"
     sleep 5
-    youtube-dl -U
-    echo \"Restarting NadekoBot...\"
+    youtube-dl -U || echo \"[ERROR] Failed to update 'youtube-dl'\" >&2
+    echo \"[INFO] Restarting NadekoBot...\"
 done
 
-echo \"Stopping NadekoBot...\"" > NadekoRun
+echo \"[INFO] Stopping NadekoBot...\"" > NadekoRun
 fi
 
 if [[ $E_SERVICE_STATUS == "active" ]]; then
