fix: 'yt-dlp' can't be found

diff --git a/nadeko-runner b/nadeko-runner
--- a/nadeko-runner
+++ b/nadeko-runner
@@ -169,7 +169,7 @@ if [[ $E_CODENAME == "NadekoRun" ]]; then
 _code_name_=\"NadekoRun\"
 
 echo \"[INFO] Running NadekoBot in the background\"
-yt-dlp -U || echo \"[ERROR] Failed to update 'yt-dlp'\" >&2
+\"$HOME/.local/bin/yt-dlp\" -U || echo \"[ERROR] Failed to update 'yt-dlp'\" >&2
 
 echo \"[INFO] Starting NadekoBot...\"
 cd $E_ROOT_DIR/nadekobot/output
@@ -187,7 +187,7 @@ else
 _code_name_=\"NadekoRunAR\"
 
 echo \"[INFO] Running NadekoBot in the background with auto restart\"
-yt-dlp -U || echo \"[ERROR] Failed to update 'yt-dlp'\" >&2
+\"$HOME/.local/bin/yt-dlp\" -U || echo \"[ERROR] Failed to update 'yt-dlp'\" >&2
 
 echo \"[INFO] Starting NadekoBot...\"
 
@@ -213,7 +213,7 @@ while true; do
 
     echo \"[INFO] Waiting 5 seconds...\"
     sleep 5
-    yt-dlp -U || echo \"[ERROR] Failed to update 'yt-dlp'\" >&2
+    \"$HOME/.local/bin/yt-dlp\" -U || echo \"[ERROR] Failed to update 'yt-dlp'\" >&2
     echo \"[INFO] Restarting NadekoBot...\"
 done
 
