func: improve error handling

diff --git a/nadeko-latest-installer b/nadeko-latest-installer
--- a/nadeko-latest-installer
+++ b/nadeko-latest-installer
@@ -92,15 +92,17 @@ cd "$E_WORKING_DIR" || E_STDERR "Failed to change directory to '$E_WORKING_DIR'"
 ### Move credentials, database, and other data to the new version of NadekoBot.
 ###
 
-if [[ ! -f $C_CURRENT_CREDS ]]; then
-    echo "${E_WARNING}'$C_CURRENT_CREDS' could not be found"
-    echo "${E_INFO}Copying '${C_EXAMPLE_CREDS##*/}' as '${C_NEW_CREDS##*/}'" \
-        "to '${C_NEW_CREDS%/*}'..."
-    cp -f "$C_EXAMPLE_CREDS" "$C_NEW_CREDS"
-else
-    echo "${E_INFO}Copying '${C_NEW_CREDS##*/}' to '${C_NEW_CREDS%/*}'..."
-    cp -f "$C_CURRENT_CREDS" "$C_NEW_CREDS"
-fi
+(
+    if [[ ! -f $C_CURRENT_CREDS ]]; then
+        echo "${E_WARNING}'$C_CURRENT_CREDS' could not be found"
+        echo "${E_INFO}Copying '${C_EXAMPLE_CREDS##*/}' as '${C_NEW_CREDS##*/}'" \
+            "to '${C_NEW_CREDS%/*}'..."
+        cp -f "$C_EXAMPLE_CREDS" "$C_NEW_CREDS" || exit 1
+    else
+        echo "${E_INFO}Copying '${C_NEW_CREDS##*/}' to '${C_NEW_CREDS%/*}'..."
+        cp -f "$C_CURRENT_CREDS" "$C_NEW_CREDS" || exit 1
+    fi
+) || E_STDERR "Failed to copy credentials" "1"
 
 
 ## If the old and new versions of NadekoBot exist, move the database and other data.
@@ -110,7 +112,8 @@ if [[ -d $C_NADEKOBOT_TMP/nadekobot && -d nadekobot ]]; then
         echo "${E_NOTE}Skipping copying the database..."
     else
         echo "${E_INFO}Copying '${C_CURRENT_DATABASE} to the '${C_NEW_DATABASE%/*}'..."
-        cp -RT "$C_CURRENT_DATABASE" "$C_NEW_DATABASE"
+        cp -RT "$C_CURRENT_DATABASE" "$C_NEW_DATABASE" \
+            || E_STDERR "Failed to copy database" "1"
     fi
 
     echo "${E_INFO}Copying other data to the new version..."
