refactor: final touch ups to comments and code

diff --git a/nadeko-latest-installer b/nadeko-latest-installer
--- a/nadeko-latest-installer
+++ b/nadeko-latest-installer
@@ -3,25 +3,24 @@
 # This script downloads and updates NadekoBot to the latest version.
 #
 # NOTE:
-#   Regarding how I manage reverting changes, I've decided to use a step-based approach
-#   compared to the state-based approach used in 'file-backup'. This is because the
-#   potential ambiguity when dealing with multiple files or directories that may or may
-#   not exist, has posed a logical challenge for me. I believe that using a step-based
-#   approach will make it easier to manage the script's logic.
+#   The end-user will have to manually re-add their strings and aliases after each
+#   update, as updates may cause a number of to become obsolete or be changed, etc.
+#   However, the old strings and aliases will be backed up as 'strings.old' and
+#   'aliases.old.yml' respectively.
 #
 # Comment Key:
 #   - A.1.: To prevent permission errors that can occur, especially when the installer
 #       is run with root privileges and later as a non-root user, it's necessary to
-#       ensure that '/tmp/NuGetScratch' and '/home/$USER/.nuget' are owned by the user
-#       currently running the installer.
+#       ensure that '/tmp/NuGetScratch' are owned by the user currently running the
+#       installer.
 #
 ########################################################################################
 ####[ Variables ]#######################################################################
 
 
-export DOTNET_CLI_TELEMETRY_OPTOUT=1  # Used when compiling code.
+export DOTNET_CLI_TELEMETRY_OPTOUT=1  # Disable .NET CLI telemetry.
 
-C_NADEKOBOT_TMP=$(mktemp -d -p /tmp nadekobot.XXXXXXXXXX)
+C_NADEKOBOT_TMP=$(mktemp -d -p /tmp nadekobot-XXXXXXXXXX)
 readonly C_NADEKOBOT_TMP
 
 readonly C_NADEKOBOT_URL="https://gitlab.com/Kwoth/nadekobot"
@@ -34,6 +33,14 @@ readonly C_CURRENT_DATA="nadekobot/output/data"
 readonly C_NEW_DATA="$C_NADEKOBOT_TMP/nadekobot/output/data"
 
 service_is_active=false
+
+if [[ -d nadekobot ]]; then
+    C_ACTION_ONE="update"
+    C_ACTION_TWO="updating"
+else
+    C_ACTION_ONE="download and set up"
+    C_ACTION_TWO="setting up"
+fi
 
 
 ####[ Functions ]#######################################################################
@@ -54,13 +61,12 @@ clean_exit() {
     local exit_code="$1"
     local use_extra_newline="${2:-false}"
 
-    # Unset the local traps to restore traps set in 'installer-prep'.
     trap - EXIT SIGINT SIGTERM SIGHUP SIGQUIT
-
     [[ $use_extra_newline == true ]] && echo ""
 
-    ## We modify the exit code to 50 to tell the 'nadeko-latest-installer', "We've had
-    ## an error, but it's safe to continue."
+    ## The exit code may be modified to 50, when 'nadeko-latest-installer' should
+    ## continue running, even if an error occurred. Please refer to the
+    ## 'exit_code_actions' function in 'nadeko-latest-installer' for more information.
     case "$exit_code" in
         1)   exit_code=50 ;;
         0|5) ;;
@@ -75,19 +81,19 @@ clean_exit() {
     esac
 
     echo "${E_INFO}Cleaning up..."
-    [[ -d "$C_NADEKOBOT_TMP" ]] && rm -rf "$C_NADEKOBOT_TMP" 2>/dev/null
+    [[ -d "$C_NADEKOBOT_TMP" ]] && rm -rf "$C_NADEKOBOT_TMP" &>/dev/null
 
     (
         if [[ -d nadekobot && ! -d nadekobot.old && -d nadekobot.old.old ]]; then
-            echo "${E_WARNING}NadekoBot is in an inconsistent state"
-            echo "${E_INFO}Attempting to restore 'nadekobot'..."
+            echo "${E_WARNING}Unable to complete installation"
+            echo "${E_INFO}Attempting to restore original version of 'nadekobot'..."
             mv nadekobot.old.old nadekobot.old || exit 1
         elif [[ ! -d nadekobot && -d nadekobot.old ]]; then
-            echo "${E_WARNING}NadekoBot is in an inconsistent state"
-            echo "${E_INFO}Attempting to restore 'nadekobot'..."
+            echo "${E_WARNING}Unable to complete installation"
+            echo "${E_INFO}Attempting to restore original version of 'nadekobot'..."
             mv nadekobot.old nadekobot || exit 1
 
-            if [[ -d "nadekobot.old.old" ]]; then
+            if [[ -d nadekobot.old.old ]]; then
                 mv nadekobot.old.old nadekobot.old \
                     || E_STDERR \
                         "Failed to rename 'nadekobot.old.old' as 'nadekobot.old'" \
@@ -99,7 +105,7 @@ clean_exit() {
                     "${E_NOTE}Please remove 'nadekobot.old.old' manually"
         fi
     ) || E_STDERR "Failed to restore 'nadekobot'" "$?" \
-        "${E_NOTE}Will exit to prevent data loss"
+        "${E_NOTE}We will exit completely to prevent data loss"
 
     read -rp "${E_NOTE}Press [Enter] to return to the main menu"
     exit "$exit_code"
@@ -119,7 +125,8 @@ trap 'clean_exit "$?" "true"'  EXIT
 ####[ Main ]############################################################################
 
 
-read -rp "${E_NOTE}We will now download/update NadekoBot. Press [Enter] to begin."
+read -rp "${E_NOTE}We will now $C_ACTION_ONE NadekoBot. Press [Enter] to begin."
+cd "$E_WORKING_DIR" || E_STDERR "Failed to change working directory" "1"
 
 ###
 ### [ Stop Service ]
@@ -131,10 +138,8 @@ if [[ $E_SERVICE_STATUS == "active" ]]; then
 fi
 
 ###
-### [ Create Backup and Update ]
+### [ Download and Compile NadekoBot ]
 ###
-
-cd "$C_NADEKOBOT_TMP" || E_STDERR "Failed to change working directory" "1"
 
 echo "${E_INFO}Downloading NadekoBot into '$C_NADEKOBOT_TMP'..."
 git clone -b "$E_BOT_INSTALL_VERSION" --recursive --depth 1 "$C_NADEKOBOT_URL" \
@@ -144,25 +149,17 @@ git clone -b "$E_BOT_INSTALL_VERSION" --recursive --depth 1 "$C_NADEKOBOT_URL" \
 if [[ -d /tmp/NuGetScratch ]]; then
     echo "${E_INFO}Modifying ownership of '/tmp/NuGetScratch'..."
     sudo chown -R "$USER":"$USER" /tmp/NuGetScratch \
-        || E_STDERR "Failed to to modify the ownership of '/tmp/NuGetScratch'" "1"
+        || E_STDERR "Failed to modify the ownership of '/tmp/NuGetScratch'" "1"
 fi
-
-## A.1.
-## Commented out because I don't believe it's necessary. But I'm leaving it here for
-## for now until I'm 100% sure it's not needed.
-#if [[ -d  /home/$USER/.nuget ]]; then
-#    echo "${E_INFO}Modifying ownership of '/home/$USER/.nuget'..."
-#    sudo chown -R "$USER":"$USER" /home/"$USER"/.nuget \
-#        || E_STDERR "Failed to to modify the ownership of '/home/$USER/.nuget'..." "1"
-#fi
 
 if [[ $E_COMPILE_NADEKOBOT == true ]]; then
     echo "${E_INFO}Building NadekoBot..."
-    cd nadekobot || E_STDERR "Failed to change directory to 'nadekobot'" "1"
+    cd nadekobot || E_STDERR "Failed to change working directory to 'nadekobot'" "1"
     dotnet restore -f --no-cache || E_STDERR "Failed to restore .NET packages" "1"
     dotnet build src/NadekoBot/NadekoBot.csproj -c Release -o output/ \
         || E_STDERR "Failed to build NadekoBot" "1"
-    cd "$E_WORKING_DIR" || E_STDERR "Failed to change directory to '$E_WORKING_DIR'" "1"
+    cd "$E_WORKING_DIR" \
+        || E_STDERR "Failed to change working directory to '$E_WORKING_DIR'" "1"
 else
     echo "${E_NOTE}'$E_COMPILE_NADEKOBOT' is set to false"
     echo "${E_NOTE}Skipping the compilation of NadekoBot..."
@@ -176,7 +173,6 @@ fi
 
 (
     if [[ ! -f $C_CURRENT_CREDS ]]; then
-        echo "${E_WARNING}'$C_CURRENT_CREDS' could not be found"
         echo "${E_INFO}Copying '${C_EXAMPLE_CREDS##*/}' as '${C_NEW_CREDS##*/}'" \
             "to '${C_NEW_CREDS%/*}'..."
         cp -f "$C_EXAMPLE_CREDS" "$C_NEW_CREDS" || exit 1
@@ -198,30 +194,25 @@ if [[ -d nadekobot ]]; then
     fi
 
     echo "${E_INFO}Copying other data to the new version..."
-
-    ### The end-user will have to manually re-add their strings after each update as
-    ### updates may cause a number of strings to become obsolete, changed, etc.
-    ### However, old user's strings will be backed up as strings_old.
-
     (
-        ## Prevent overwriting the new strings directory and aliases.yml file, by renaming
-        ## them.
-        mv -fT "$C_NEW_DATA"/strings "$C_NEW_DATA"/strings_new || exit 1
-        mv -f "$C_NEW_DATA"/aliases.yml "$C_NEW_DATA"/aliases_new.yml || exit 1
+        ## Prevent overwriting the new strings directory and aliases.yml file, by
+        ## renaming them.
+        mv -fT "$C_NEW_DATA"/strings "$C_NEW_DATA"/strings.new || exit 1
+        mv -f "$C_NEW_DATA"/aliases.yml "$C_NEW_DATA"/aliases.new.yml || exit 1
 
         # Copy current data directory to new data directory. This will overwrite any
         # file or directory that exists in the new data directory, with the same name.
         cp -rT "$C_CURRENT_DATA" "$C_NEW_DATA" || exit 1
 
         # Remove old strings and aliases.
-        rm -rf "$C_NEW_DATA"/strings_old "$C_NEW_DATA"/aliases_old.yml 2>/dev/null
-        ## Back up old strings and aliases.
-        mv -fT "$C_NEW_DATA"/strings "$C_NEW_DATA"/strings_old || exit 1
-        mv -f "$C_NEW_DATA"/aliases.yml "$C_NEW_DATA"/aliases_old.yml || exit 1
+        rm -rf "$C_NEW_DATA"/strings.old "$C_NEW_DATA"/aliases.old.yml 2>/dev/null
+        ## Back up new-old strings and aliases.
+        mv -fT "$C_NEW_DATA"/strings "$C_NEW_DATA"/strings.old || exit 1
+        mv -f "$C_NEW_DATA"/aliases.yml "$C_NEW_DATA"/aliases.old.yml || exit 1
 
         ## Restore new strings and aliases.
-        mv -fT "$C_NEW_DATA"/strings_new "$C_NEW_DATA"/strings || exit 1
-        mv -f "$C_NEW_DATA"/aliases_new.yml "$C_NEW_DATA"/aliases.yml || exit 1
+        mv -fT "$C_NEW_DATA"/strings.new "$C_NEW_DATA"/strings || exit 1
+        mv -f "$C_NEW_DATA"/aliases.new.yml "$C_NEW_DATA"/aliases.yml || exit 1
     ) || E_STDERR "An error occurred while copying other data" "$?"
 
     echo "${E_INFO}Replacing 'nadekobot' with '${C_NADEKOBOT_TMP}/nadekobot'..."
@@ -243,7 +234,7 @@ if [[ -d nadekobot ]]; then
     ) || E_STDERR "An error occurred while replacing 'nadekobot'" "$?"
 else
     echo "${E_INFO}Moving '$C_NADEKOBOT_TMP/nadekobot' to 'nadekobot'..."
-    mv "$C_NADEKOBOT_TMP"/nadekobot . \
+    mv "$C_NADEKOBOT_TMP"/nadekobot "$E_WORKING_DIR" \
         || E_STDERR "Failed to move '${C_NADEKOBOT_TMP}' to 'nadekobot'" "1"
     rmdir "$C_NADEKOBOT_TMP" &>/dev/null
 fi
@@ -253,11 +244,9 @@ fi
 ###
 
 echo ""
-echo "${E_SUCCESS}Finished downloading/updating NadekoBot"
+echo "${E_SUCCESS}Finished $C_ACTION_TWO NadekoBot"
 
 if [[ $service_is_active == true ]]; then
     echo "${E_NOTE}'$E_SERVICE_NAME' was stopped to update NadekoBot and needs to be" \
         "started using one of the run modes in the installer menu"
 fi
-
-clean_exit 0
