Improve how dotnet is delt with

diff --git a/prereqs-installer b/prereqs-installer
--- a/prereqs-installer
+++ b/prereqs-installer
@@ -35,27 +35,35 @@ install_prereqs() {
     sudo dpkg -i packages-microsoft-prod.deb
     sudo rm -f packages-microsoft-prod.deb
 
-    ### TODO: Think of a better way to resolve possible problems where something might
-    ###       go wrong here.
+    ### TODO: Provide better comments to explain this section
     if [[ $4 = true ]]; then
-        if [[ ! -f /etc/apt/preferences.d/custom-dotnet.pref ]]; then
-            echo -e "Explanation: https://github.com/dotnet/core/issues/7699" \
-                "\nPackage: *" \
-                "\nPin: origin \"packages.microsoft.com\"" \
-                "\nPin-Priority: 1001" | sudo tee /etc/apt/preferences.d/custom-dotnet.pref \
-            || {
-                echo "${_RED}Failed to create" \
-                    "'/etc/apt/preferences.d/custom-dotnet.pref'${_NC}" >&2
-                exit 1
-            }
+        if hash dotnet && [[ ! $(dotnet --version &>/dev/null) ]]; then
+            echo "${_YELLOW}While the .NET runtime is installed, the .NET SDK is not${_NC}"
+            echo "Uninstalling existing .NET Core 6.0 installation..."
+            sudo apt remove dotnet-sdk-6.0 -y
+            sudo apt autoremove -y
 
+            if [[ ! -f /etc/apt/preferences.d/custom-dotnet.pref ]]; then
+                echo "Upating prefered .NET Core install method..."
+
+                {
+                    echo -e "Explanation: https://github.com/dotnet/core/issues/7699" \
+                        "\nPackage: *" \
+                        "\nPin: origin \"packages.microsoft.com\"" \
+                        "\nPin-Priority: 1001" | sudo tee /etc/apt/preferences.d/custom-dotnet.pref
+                } || {
+                    echo "${_RED}Failed to create" \
+                        "'/etc/apt/preferences.d/custom-dotnet.pref'${_NC}" >&2
+                    exit 1
+                }
+
+                echo "Reinstalling .NET Core..."
+            fi
         fi
     fi
 
     ## Install the SDK.
-    sudo apt-get update
-    sudo apt-get install -y apt-transport-https \
-        && sudo apt-get update \
+    sudo apt-get update \
         && sudo apt-get install -y dotnet-sdk-6.0
 
     ## Install music prerequisites.
@@ -64,7 +72,7 @@ install_prereqs() {
 
     ## Other prerequisites.
     echo "Installing other prerequisites..."
-    sudo apt-get install ffmpeg redis-server git python3 "$3" ccze -y
+    sudo apt-get install ffmpeg redis-server git apt-transport-https python3 "$3" ccze -y
     sudo curl -s -L https://yt-dl.org/downloads/latest/youtube-dl -o \
         /usr/local/bin/youtube-dl
     # A.1. & B.1.
