docs: add function comments regarding exit actions

diff --git a/prereqs-installer b/prereqs-installer
--- a/prereqs-installer
+++ b/prereqs-installer
@@ -33,6 +33,9 @@ readonly C_OTHER_PREREQS=("redis-server" "git" "ccze" "apt-transport-https" "ffm
 #       - Acceptable values:
 #           - true
 #           - false
+#
+# EXITS:
+#   - $exit_code: Argument provided by the caller, or 50 if the exit code is 1 or 130.
 clean_exit() {
     local exit_code="$1"
     local use_extra_newline="${2:-false}"
@@ -79,6 +82,9 @@ clean_exit() {
 
 ####
 # Install 'yt-dlp' at '~/.local/bin/yt-dlp'.
+#
+# EXITS:
+#   - 1: Failed to download 'yt-dlp'.
 install_yt_dlp() {
     local yt_dlp_url="https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp"
     local yt_dpl_dir="${E_YT_DLP_PATH%/*}"
@@ -108,6 +114,11 @@ install_yt_dlp() {
 #       - Acceptable values:
 #           - true
 #           - false
+#
+# EXITS:
+#   - 0: Successfully installed all prerequisites.
+#   - 1: Failed to add Microsoft's package signing key.
+#   - $?: Failed to install all prerequisites or remove existing .NET installation.
 install_prereqs() {
     local distro_name="$1"
     local distro_ver="$2"
@@ -160,6 +171,9 @@ install_prereqs() {
 
 ####
 # Display a message indicating that the installer does not support the current OS.
+#
+# EXITS:
+#   - 4: The installer does not support the current OS.
 unsupported() {
     echo "${E_ERROR}The installer does not support the automatic installation and" \
         "setup of NadekoBot's prerequisites for your OS: $E_DISTRO $E_VER $E_ARCH" >&2
