feat: users can now safely use 'Ctrl' + 'C' to cancel the installation of prerequisites

diff --git a/prereqs-installer b/prereqs-installer
--- a/prereqs-installer
+++ b/prereqs-installer
@@ -86,8 +86,9 @@ install_prereqs() {
         if (hash dotnet &>/dev/null && [[ ! $(dotnet --version) ]]) &>/dev/null; then
             echo "${E_WARNING}While the .NET runtime is installed, the .NET SDK is not"
             echo "${E_INFO}Uninstalling existing .NET Core installation..."
-            sudo apt remove -y "$C_REQ_DOTNET_PKG"
-            sudo apt autoremove -y
+            ( sudo apt remove -y "$C_REQ_DOTNET_PKG" && sudo apt autoremove -y ) &
+            APT_PID=$!
+            wait $APT_PID
         fi
 
         if [[ ! -f /etc/apt/preferences.d/custom-dotnet.pref ]]; then
@@ -100,24 +101,27 @@ install_prereqs() {
         fi
     fi
 
-    #(
-    echo "${E_INFO}Installing .NET Core..."
-    sudo apt update && sudo apt install -y "$C_REQ_DOTNET_PKG" #|| exit 1
+    (
+        echo "${E_INFO}Installing .NET Core..."
+        sudo apt update && sudo apt install -y "$C_REQ_DOTNET_PKG" || exit 1
 
-    echo "${E_INFO}Installing music prerequisites..."
-    sudo apt install -y "${C_MUSIC_PREREQS[@]}" #|| exit 1
+        echo "${E_INFO}Installing music prerequisites..."
+        sudo apt install -y "${C_MUSIC_PREREQS[@]}" || exit 1
 
-    echo "${E_INFO}Installing other prerequisites..."
-    sudo apt install -y "${C_OTHER_PREREQS[@]}" "$python_pkg" #|| exit 1
+        echo "${E_INFO}Installing other prerequisites..."
+        sudo apt install -y "${C_OTHER_PREREQS[@]}" "$python_pkg" || exit 1
 
-    sudo curl -s -L "$C_YT_DL_URL" -o "$C_YT_DL_PATH" #|| exit 1
-    # If the write perms are not applied to all users for this tool, attempts to
-    # update 'youtube-dl' by a non-root user will always fail.
-    # TODO: Find a better solution than modifying the perms.
-    sudo chmod a+rwx "$C_YT_DL_PATH" #|| exit 1
-    #) &
-    #APT_PID=$!
-    #wait $APT_PID
+        sudo curl -s -L "$C_YT_DL_URL" -o "$C_YT_DL_PATH" || exit 1
+        echo "${E_INFO}Modifying permissions for 'youtube-dl'..."
+        # If the write perms are not applied to all users for this tool, attempts to
+        # update 'youtube-dl' by a non-root user will always fail.
+        # TODO: Find a better solution than modifying the perms.
+        sudo chmod a+rwx "$C_YT_DL_PATH" \
+            || E_STDERR "Failed to modify permissions as 'a+rwx' for '$C_YT_DL_PATH'" \
+                "1" "${E_NOTE}Permission errors may occur when updating 'youtube-dl'"
+    ) &
+    APT_PID=$!
+    wait $APT_PID
 
     echo -e "\n${E_SUCCESS}Finished installing prerequisites"
     exit 0
